import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CidadesService {
  cidades: any = [
    { sigla: 'AC', descricao: 'CAPIXABA' },
    { sigla: 'AC', descricao: 'CRUZEIRO DO SUL' },
    { sigla: 'AC', descricao: 'RIO BRANCO' },
    { sigla: 'AC', descricao: 'SENADOR GUIOMARD' },
    { sigla: 'AL', descricao: 'ALAGOAS' },
    { sigla: 'AL', descricao: 'ARAPIRACA' },
    { sigla: 'AL', descricao: 'ATALAIA' },
    { sigla: 'AL', descricao: 'CORURIPE' },
    { sigla: 'AL', descricao: 'IGREJA NOVA' },
    { sigla: 'AL', descricao: 'MACEIO' },
    { sigla: 'AL', descricao: 'MARECHAL DEODORO' },
    { sigla: 'AL', descricao: 'MURICI' },
    { sigla: 'AL', descricao: 'RIO LARGO' },
    { sigla: 'AL', descricao: 'SAO MIGUEL DOS CAMPOS' },
    { sigla: 'AM', descricao: 'BOCA DO ACRE' },
    { sigla: 'AM', descricao: 'MANAUS' },
    { sigla: 'AM', descricao: 'PAUINI' },
    { sigla: 'AM', descricao: 'PRESIDENTE FIGUEIREDO' },
    { sigla: 'AM', descricao: 'TEFE' },
    { sigla: 'AP', descricao: 'LARANJAL DO JARI' },
    { sigla: 'AP', descricao: 'MACAPA' },
    { sigla: 'AP', descricao: 'SANTANA' },
    { sigla: 'BA', descricao: 'AMARGOSA' },
    { sigla: 'BA', descricao: 'BARRA' },
    { sigla: 'BA', descricao: 'BARREIRAS' },
    { sigla: 'BA', descricao: 'BREJOES' },
    { sigla: 'BA', descricao: 'CAMACARI' },
    { sigla: 'BA', descricao: 'CAMPO ALEGRE DE LOURDES' },
    { sigla: 'BA', descricao: 'CAMPO FORMOSO' },
    { sigla: 'BA', descricao: 'CANDEIAS' },
    { sigla: 'BA', descricao: 'CONCEIÇÃO DO COITE' },
    { sigla: 'BA', descricao: 'CORRENTINA' },
    { sigla: 'BA', descricao: 'CRUZ DAS ALMAS' },
    { sigla: 'BA', descricao: 'DIAS D AVILA' },
    { sigla: 'BA', descricao: 'EUNAPOLIS' },
    { sigla: 'BA', descricao: 'FEIRA DE SANTANA' },
    { sigla: 'BA', descricao: 'GUANAMBI' },
    { sigla: 'BA', descricao: 'IBIRAPUA' },
    { sigla: 'BA', descricao: 'ILHEUS' },
    { sigla: 'BA', descricao: 'IRECE' },
    { sigla: 'BA', descricao: 'ITABERABA' },
    { sigla: 'BA', descricao: 'ITABUNA' },
    { sigla: 'BA', descricao: 'ITAPEBI' },
    { sigla: 'BA', descricao: 'ITAPETINGA' },
    { sigla: 'BA', descricao: 'JACOBINA' },
    { sigla: 'BA', descricao: 'JEQUIE' },
    { sigla: 'BA', descricao: 'LAURO DE FREITAS' },
    { sigla: 'BA', descricao: 'LUIS EDUARDO MAGALHAES' },
    { sigla: 'BA', descricao: 'MUCURI' },
    { sigla: 'BA', descricao: 'NOVA VICOSA' },
    { sigla: 'BA', descricao: 'PRADO' },
    { sigla: 'BA', descricao: 'SALVADOR' },
    { sigla: 'BA', descricao: 'SANTO ANTONIO DE JESUS' },
    { sigla: 'BA', descricao: 'SAO DESIDERIO' },
    { sigla: 'BA', descricao: 'SAO FRANCISCO DO CONDE' },
    { sigla: 'BA', descricao: 'SAO SEBASTIAO DO PASSE' },
    { sigla: 'BA', descricao: 'SAPEACU' },
    { sigla: 'BA', descricao: 'SIMOES FILHO' },
    { sigla: 'BA', descricao: 'TEIXEIRA DE FREITAS' },
    { sigla: 'BA', descricao: 'TEOFILANDIA' },
    { sigla: 'BA', descricao: 'UNA' },
    { sigla: 'BA', descricao: 'URUCUCA' },
    { sigla: 'BA', descricao: 'VITORIA DA CONQUISTA' },
    { sigla: 'CE', descricao: 'CAUCAIA' },
    { sigla: 'CE', descricao: 'EUSEBIO' },
    { sigla: 'CE', descricao: 'FORTALEZA' },
    { sigla: 'CE', descricao: 'IGUATU' },
    { sigla: 'CE', descricao: 'ITAICABA' },
    { sigla: 'CE', descricao: 'ITAITINGA' },
    { sigla: 'CE', descricao: 'JUAZEIRO DO NORTE' },
    { sigla: 'CE', descricao: 'LIMOEIRO DO NORTE' },
    { sigla: 'CE', descricao: 'MARACANAU' },
    { sigla: 'CE', descricao: 'PACAJUS' },
    { sigla: 'CE', descricao: 'PACATUBA' },
    { sigla: 'CE', descricao: 'PARAIPABA' },
    { sigla: 'CE', descricao: 'QUIXERE' },
    { sigla: 'CE', descricao: 'SAO GONCALO DO AMARANTE' },
    { sigla: 'CE', descricao: 'VARZEA ALEGRE' },
    { sigla: 'DF', descricao: 'BRASILIA' },
    { sigla: 'ES', descricao: 'AFONSO CLAUDIO' },
    { sigla: 'ES', descricao: 'ANCHIETA' },
    { sigla: 'ES', descricao: 'ARACRUZ' },
    { sigla: 'ES', descricao: 'BAIXO GUANDU' },
    { sigla: 'ES', descricao: 'BARRA DE SÃO FRANCISCO' },
    { sigla: 'ES', descricao: 'BOM JESUS DO NORTE' },
    { sigla: 'ES', descricao: 'BREJETUBA' },
    { sigla: 'ES', descricao: 'CACHOEIRO DE ITAPEMIRIM' },
    { sigla: 'ES', descricao: 'CARIACICA' },
    { sigla: 'ES', descricao: 'COLATINA' },
    { sigla: 'ES', descricao: 'CONCEICAO DA BARRA' },
    { sigla: 'ES', descricao: 'GUARAPARI' },
    { sigla: 'ES', descricao: 'ICONHA' },
    { sigla: 'ES', descricao: 'LINHARES' },
    { sigla: 'ES', descricao: 'MARECHAL FLORIANO' },
    { sigla: 'ES', descricao: 'MIMOSO DO SUL' },
    { sigla: 'ES', descricao: 'PEDRO CANARIO' },
    { sigla: 'ES', descricao: 'SANTA MARIA DE JETIBA' },
    { sigla: 'ES', descricao: 'SAO MATEUS' },
    { sigla: 'ES', descricao: 'SERRA' },
    { sigla: 'ES', descricao: 'SOORETAMA' },
    { sigla: 'ES', descricao: 'VENDA NOVA DO IMIGRANTE' },
    { sigla: 'ES', descricao: 'VIANA' },
    { sigla: 'ES', descricao: 'VILA VELHA' },
    { sigla: 'ES', descricao: 'VITORIA' },
    { sigla: 'EX', descricao: 'EXTERIOR' },
    { sigla: 'GO', descricao: 'ABADIANIA' },
    { sigla: 'GO', descricao: 'ACREUNA' },
    { sigla: 'GO', descricao: 'AGUAS LINDAS DE GOIAS' },
    { sigla: 'GO', descricao: 'ALEXANIA' },
    { sigla: 'GO', descricao: 'ANAPOLIS' },
    { sigla: 'GO', descricao: 'ANICUNS' },
    { sigla: 'GO', descricao: 'APARECIDA DE GOIANIA' },
    { sigla: 'GO', descricao: 'APORE' },
    { sigla: 'GO', descricao: 'ARENOPOLIS' },
    { sigla: 'GO', descricao: 'BARRO ALTO' },
    { sigla: 'GO', descricao: 'BOM JESUS DE GOIAS' },
    { sigla: 'GO', descricao: 'BRAZABRANTES' },
    { sigla: 'GO', descricao: 'CACHOEIRA ALTA' },
    { sigla: 'GO', descricao: 'CACHOEIRA DOURADA' },
    { sigla: 'GO', descricao: 'CACU' },
    { sigla: 'GO', descricao: 'CALDAS NOVA' },
    { sigla: 'GO', descricao: 'CAMPO LIMPO DE GOIAS' },
    { sigla: 'GO', descricao: 'CARMO DO RIO VERDE' },
    { sigla: 'GO', descricao: 'CATALAO' },
    { sigla: 'GO', descricao: 'CAVALCANTE' },
    { sigla: 'GO', descricao: 'CERES' },
    { sigla: 'GO', descricao: 'CEZARINA' },
    { sigla: 'GO', descricao: 'CHAPADÃO DO CEÚ' },
    { sigla: 'GO', descricao: 'CIDADE OCIDENTAL' },
    { sigla: 'GO', descricao: 'CORUMBAIBA' },
    { sigla: 'GO', descricao: 'CRISTALINA' },
    { sigla: 'GO', descricao: 'DAVINOPOLIS' },
    { sigla: 'GO', descricao: 'EDEIA' },
    { sigla: 'GO', descricao: 'GOIANESIA' },
    { sigla: 'GO', descricao: 'GOIANIA' },
    { sigla: 'GO', descricao: 'GOIANIRA' },
    { sigla: 'GO', descricao: 'GOIAS' },
    { sigla: 'GO', descricao: 'GOIATUBA' },
    { sigla: 'GO', descricao: 'GUAPO' },
    { sigla: 'GO', descricao: 'HIDROLANDIA' },
    { sigla: 'GO', descricao: 'INHUMAS' },
    { sigla: 'GO', descricao: 'IPAMERI' },
    { sigla: 'GO', descricao: 'IPORA' },
    { sigla: 'GO', descricao: 'ITABERAI' },
    { sigla: 'GO', descricao: 'ITAPACI' },
    { sigla: 'GO', descricao: 'ITAPURANGA' },
    { sigla: 'GO', descricao: 'ITARUMA' },
    { sigla: 'GO', descricao: 'ITUMBIARA' },
    { sigla: 'GO', descricao: 'JANDAIA' },
    { sigla: 'GO', descricao: 'JATAI' },
    { sigla: 'GO', descricao: 'JUSSARA' },
    { sigla: 'GO', descricao: 'LEOPOLDO DE BULHOES' },
    { sigla: 'GO', descricao: 'LUZIANIA' },
    { sigla: 'GO', descricao: 'MARA ROSA' },
    { sigla: 'GO', descricao: 'MINACU' },
    { sigla: 'GO', descricao: 'MINEIROS' },
    { sigla: 'GO', descricao: 'MONTIVIDIU' },
    { sigla: 'GO', descricao: 'MORRINHOS' },
    { sigla: 'GO', descricao: 'MOZARLANDIA' },
    { sigla: 'GO', descricao: 'NEROPOLIS' },
    { sigla: 'GO', descricao: 'NOVA CRIXAS' },
    { sigla: 'GO', descricao: 'NOVA ROMA' },
    { sigla: 'GO', descricao: 'ORIZONA' },
    { sigla: 'GO', descricao: 'PADRE BERNARDO' },
    { sigla: 'GO', descricao: 'PALMEIRAS DE GOIAS' },
    { sigla: 'GO', descricao: 'PANAMA' },
    { sigla: 'GO', descricao: 'PARAUNA' },
    { sigla: 'GO', descricao: 'PEROLANDIA' },
    { sigla: 'GO', descricao: 'PIRACANJUBA' },
    { sigla: 'GO', descricao: 'PIRES DO RIO' },
    { sigla: 'GO', descricao: 'PORANGATU' },
    { sigla: 'GO', descricao: 'PORTEIRAO' },
    { sigla: 'GO', descricao: 'QUIRINOPOLIS' },
    { sigla: 'GO', descricao: 'RIO VERDE' },
    { sigla: 'GO', descricao: 'RUBIATABA' },
    { sigla: 'GO', descricao: 'SANTA HELENA DE GOIAS' },
    { sigla: 'GO', descricao: 'SANTO ANTONIO DA BARRA' },
    { sigla: 'GO', descricao: 'SAO LUIS DE MONTES BELOS' },
    { sigla: 'GO', descricao: 'SAO SIMAO' },
    { sigla: 'GO', descricao: 'SENADOR CANEDO' },
    { sigla: 'GO', descricao: 'SERRANOPOLIS' },
    { sigla: 'GO', descricao: 'SILVANIA' },
    { sigla: 'GO', descricao: 'TEREZOPOLIS DE GOIAS' },
    { sigla: 'GO', descricao: 'TRINDADE' },
    { sigla: 'GO', descricao: 'TURVELANDIA' },
    { sigla: 'GO', descricao: 'URUACU' },
    { sigla: 'GO', descricao: 'VALPARAISO DE GOIAS' },
    { sigla: 'GO', descricao: 'VICENTINOPOLIS' },
    { sigla: 'MA', descricao: 'ACAILANDIA' },
    { sigla: 'MA', descricao: 'BACABEIRA' },
    { sigla: 'MA', descricao: 'CHAPADINHA' },
    { sigla: 'MA', descricao: 'GRAJAU' },
    { sigla: 'MA', descricao: 'IMPERATRIZ' },
    { sigla: 'MA', descricao: 'LAJEADO NOVO' },
    { sigla: 'MA', descricao: 'LIMA CAMPOS' },
    { sigla: 'MA', descricao: 'PINHEIRO' },
    { sigla: 'MA', descricao: 'S.RAIMUNDO DA MANGABEIRAS' },
    { sigla: 'MA', descricao: 'SANTA INES' },
    { sigla: 'MA', descricao: 'SAO JOSE DE RIBAMAR' },
    { sigla: 'MA', descricao: 'SAO LUIS' },
    { sigla: 'MG', descricao: 'AGUA COMPRIDA' },
    { sigla: 'MG', descricao: 'ALBERTINA' },
    { sigla: 'MG', descricao: 'ALEM PARAIBA' },
    { sigla: 'MG', descricao: 'ALFENAS' },
    { sigla: 'MG', descricao: 'ALPINOPOLIS' },
    { sigla: 'MG', descricao: 'ALTEROSA' },
    { sigla: 'MG', descricao: 'ANDRADAS' },
    { sigla: 'MG', descricao: 'ANDRELÂNDIA' },
    { sigla: 'MG', descricao: 'ARAGUARI' },
    { sigla: 'MG', descricao: 'ARAPORA' },
    { sigla: 'MG', descricao: 'ARAPUA' },
    { sigla: 'MG', descricao: 'ARAXA' },
    { sigla: 'MG', descricao: 'ARCEBURGO' },
    { sigla: 'MG', descricao: 'ARCOS' },
    { sigla: 'MG', descricao: 'AREADO' },
    { sigla: 'MG', descricao: 'ARICANDUVA' },
    { sigla: 'MG', descricao: 'BANDEIRA DO SUL' },
    { sigla: 'MG', descricao: 'BARAO DE COCAIS' },
    { sigla: 'MG', descricao: 'BARBACENA' },
    { sigla: 'MG', descricao: 'BARROSO' },
    { sigla: 'MG', descricao: 'BELA VISTA DE MINAS' },
    { sigla: 'MG', descricao: 'BELMIRO BRAGA' },
    { sigla: 'MG', descricao: 'BELO HORIZONTE' },
    { sigla: 'MG', descricao: 'BELO ORIENTE' },
    { sigla: 'MG', descricao: 'BELO VALE' },
    { sigla: 'MG', descricao: 'BETIM' },
    { sigla: 'MG', descricao: 'BOA ESPERANCA' },
    { sigla: 'MG', descricao: 'BOCAIUVA' },
    { sigla: 'MG', descricao: 'BOM DESPACHO' },
    { sigla: 'MG', descricao: 'BONITO DE MINAS' },
    { sigla: 'MG', descricao: 'BORDA DA MATA' },
    { sigla: 'MG', descricao: 'BOTELHOS' },
    { sigla: 'MG', descricao: 'BRASILANDIA DE MINAS' },
    { sigla: 'MG', descricao: 'BUENO BRANDAO' },
    { sigla: 'MG', descricao: 'CAETE' },
    { sigla: 'MG', descricao: 'CALDAS' },
    { sigla: 'MG', descricao: 'CAMANDUCAIA' },
    { sigla: 'MG', descricao: 'CAMBUI' },
    { sigla: 'MG', descricao: 'CAMPANHA' },
    { sigla: 'MG', descricao: 'CAMPESTRE' },
    { sigla: 'MG', descricao: 'CAMPINA VERDE' },
    { sigla: 'MG', descricao: 'CAMPO BELO' },
    { sigla: 'MG', descricao: 'CAMPO FLORIDO' },
    { sigla: 'MG', descricao: 'CAMPOS GERAIS' },
    { sigla: 'MG', descricao: 'CANAPOLIS' },
    { sigla: 'MG', descricao: 'CAPELINHA' },
    { sigla: 'MG', descricao: 'CAPINOPOLIS' },
    { sigla: 'MG', descricao: 'CARATINGA' },
    { sigla: 'MG', descricao: 'CARMO DA CACHOEIRA' },
    { sigla: 'MG', descricao: 'CARMO DA MATA' },
    { sigla: 'MG', descricao: 'CARMO DO CAJURU' },
    { sigla: 'MG', descricao: 'CARMO DO PARANAIBA' },
    { sigla: 'MG', descricao: 'CARMO DO RIO CLARO' },
    { sigla: 'MG', descricao: 'CARMOPOLIS DE MINAS' },
    { sigla: 'MG', descricao: 'CARNEIRINHO' },
    { sigla: 'MG', descricao: 'CARRANCAS' },
    { sigla: 'MG', descricao: 'CATAGUASES' },
    { sigla: 'MG', descricao: 'CAXAMBU' },
    { sigla: 'MG', descricao: 'CENTRALINA' },
    { sigla: 'MG', descricao: 'CLAUDIO' },
    { sigla: 'MG', descricao: 'CONCEICAO DAS ALAGOAS' },
    { sigla: 'MG', descricao: 'CONCEICAO DOS OUROS' },
    { sigla: 'MG', descricao: 'CONFINS' },
    { sigla: 'MG', descricao: 'CONGONHAL' },
    { sigla: 'MG', descricao: 'CONQUISTA' },
    { sigla: 'MG', descricao: 'CONSELHEIRO LAFAIETE' },
    { sigla: 'MG', descricao: 'CONTAGEM' },
    { sigla: 'MG', descricao: 'COQUEIRAL' },
    { sigla: 'MG', descricao: 'CORONEL FABRICIANO' },
    { sigla: 'MG', descricao: 'CORREGO DO BOM JESUS' },
    { sigla: 'MG', descricao: 'CRISTAIS' },
    { sigla: 'MG', descricao: 'CRUZILIA' },
    { sigla: 'MG', descricao: 'DELTA' },
    { sigla: 'MG', descricao: 'DIAMANTINA' },
    { sigla: 'MG', descricao: 'DIVINO' },
    { sigla: 'MG', descricao: 'DIVINOPOLIS' },
    { sigla: 'MG', descricao: 'DOM SILVERIO' },
    { sigla: 'MG', descricao: 'ELOI MENDES' },
    { sigla: 'MG', descricao: 'ENTRE RIOS DE MINAS' },
    { sigla: 'MG', descricao: 'ESMERALDAS' },
    { sigla: 'MG', descricao: 'ESPERA FELIZ' },
    { sigla: 'MG', descricao: 'ESTIVA' },
    { sigla: 'MG', descricao: 'EXTREMA' },
    { sigla: 'MG', descricao: 'FLORESTAL' },
    { sigla: 'MG', descricao: 'FORMIGA' },
    { sigla: 'MG', descricao: 'FRONTEIRA' },
    { sigla: 'MG', descricao: 'FRUTAL' },
    { sigla: 'MG', descricao: 'GOVERNADOR VALADARES' },
    { sigla: 'MG', descricao: 'GUANHAES' },
    { sigla: 'MG', descricao: 'GUARANESIA' },
    { sigla: 'MG', descricao: 'GUAXUPE' },
    { sigla: 'MG', descricao: 'GUIDOVAL' },
    { sigla: 'MG', descricao: 'GUIMARANIA' },
    { sigla: 'MG', descricao: 'IBIA' },
    { sigla: 'MG', descricao: 'IBIRACI' },
    { sigla: 'MG', descricao: 'IBIRITE' },
    { sigla: 'MG', descricao: 'IBITIURA DE MINAS' },
    { sigla: 'MG', descricao: 'IGARAPE' },
    { sigla: 'MG', descricao: 'IGUATAMA' },
    { sigla: 'MG', descricao: 'IJACI' },
    { sigla: 'MG', descricao: 'INCONFIDENTES' },
    { sigla: 'MG', descricao: 'INDAIABIRA' },
    { sigla: 'MG', descricao: 'IPATINGA' },
    { sigla: 'MG', descricao: 'IPUIUNA' },
    { sigla: 'MG', descricao: 'IRAI DE MINAS' },
    { sigla: 'MG', descricao: 'ITABIRA' },
    { sigla: 'MG', descricao: 'ITABIRITO' },
    { sigla: 'MG', descricao: 'ITAGUARA' },
    { sigla: 'MG', descricao: 'ITAJUBA' },
    { sigla: 'MG', descricao: 'ITAMOGI' },
    { sigla: 'MG', descricao: 'ITAMONTE' },
    { sigla: 'MG', descricao: 'ITANHANDU' },
    { sigla: 'MG', descricao: 'ITAPAGIPE' },
    { sigla: 'MG', descricao: 'ITAPECIRICA' },
    { sigla: 'MG', descricao: 'ITAPEVA' },
    { sigla: 'MG', descricao: 'ITAU DE MINAS' },
    { sigla: 'MG', descricao: 'ITAUNA' },
    { sigla: 'MG', descricao: 'ITUIUTABA' },
    { sigla: 'MG', descricao: 'ITURAMA' },
    { sigla: 'MG', descricao: 'JABOTICATUBAS' },
    { sigla: 'MG', descricao: 'JACUTINGA' },
    { sigla: 'MG', descricao: 'JAIBA' },
    { sigla: 'MG', descricao: 'JANAUBA' },
    { sigla: 'MG', descricao: 'JOAO MONLEVADE' },
    { sigla: 'MG', descricao: 'JOAO PINHEIRO' },
    { sigla: 'MG', descricao: 'JUATUBA' },
    { sigla: 'MG', descricao: 'JUIZ DE FORA' },
    { sigla: 'MG', descricao: 'LAGAMAR' },
    { sigla: 'MG', descricao: 'LAGOA DA PRATA' },
    { sigla: 'MG', descricao: 'LAGOA FORMOSA' },
    { sigla: 'MG', descricao: 'LAGOA SANTA' },
    { sigla: 'MG', descricao: 'LAMBARI' },
    { sigla: 'MG', descricao: 'LAVRAS' },
    { sigla: 'MG', descricao: 'LEOPOLDINA' },
    { sigla: 'MG', descricao: 'LIMEIRA DO OESTE' },
    { sigla: 'MG', descricao: 'MACHADO' },
    { sigla: 'MG', descricao: 'MANHUACU' },
    { sigla: 'MG', descricao: 'MARIANA' },
    { sigla: 'MG', descricao: 'MATEUS LEME' },
    { sigla: 'MG', descricao: 'MATIAS BARBOSA' },
    { sigla: 'MG', descricao: 'MATOZINHOS' },
    { sigla: 'MG', descricao: 'MONSENHOR PAULO' },
    { sigla: 'MG', descricao: 'MONTE ALEGRE DE MINAS' },
    { sigla: 'MG', descricao: 'MONTE BELO' },
    { sigla: 'MG', descricao: 'MONTE CARMELO' },
    { sigla: 'MG', descricao: 'MONTE SANTO DE MINAS' },
    { sigla: 'MG', descricao: 'MONTE SIAO' },
    { sigla: 'MG', descricao: 'MONTES CLAROS' },
    { sigla: 'MG', descricao: 'MUNHOZ' },
    { sigla: 'MG', descricao: 'MURIAE' },
    { sigla: 'MG', descricao: 'MUZAMBINHO' },
    { sigla: 'MG', descricao: 'NATERCIA' },
    { sigla: 'MG', descricao: 'NAZARENO' },
    { sigla: 'MG', descricao: 'NOVA ERA' },
    { sigla: 'MG', descricao: 'NOVA LIMA' },
    { sigla: 'MG', descricao: 'NOVA SERRANA' },
    { sigla: 'MG', descricao: 'OLIVEIRA' },
    { sigla: 'MG', descricao: 'OURO BRANCO' },
    { sigla: 'MG', descricao: 'OURO FINO' },
    { sigla: 'MG', descricao: 'PAINS' },
    { sigla: 'MG', descricao: 'PARA DE MINAS' },
    { sigla: 'MG', descricao: 'PARACATU' },
    { sigla: 'MG', descricao: 'PARAGUACU' },
    { sigla: 'MG', descricao: 'PARAISOPOLIS' },
    { sigla: 'MG', descricao: 'PASSA QUATRO' },
    { sigla: 'MG', descricao: 'PASSOS' },
    { sigla: 'MG', descricao: 'PATOS DE MINAS' },
    { sigla: 'MG', descricao: 'PATROCINIO' },
    { sigla: 'MG', descricao: 'PEDRALVA' },
    { sigla: 'MG', descricao: 'PEDRINOPOLIS' },
    { sigla: 'MG', descricao: 'PEDRO LEOPOLDO' },
    { sigla: 'MG', descricao: 'PERDIZES' },
    { sigla: 'MG', descricao: 'PIRAJUBA' },
    { sigla: 'MG', descricao: 'PIRAPORA' },
    { sigla: 'MG', descricao: 'PIRAUBA' },
    { sigla: 'MG', descricao: 'PLANURA' },
    { sigla: 'MG', descricao: 'POCOS DE CALDAS' },
    { sigla: 'MG', descricao: 'POMPEU' },
    { sigla: 'MG', descricao: 'PONTE NOVA' },
    { sigla: 'MG', descricao: 'POUSO ALEGRE' },
    { sigla: 'MG', descricao: 'PRATA' },
    { sigla: 'MG', descricao: 'PRESIDENTE OLEGARIO' },
    { sigla: 'MG', descricao: 'RIBEIRAO DAS NEVES' },
    { sigla: 'MG', descricao: 'RIO ACIMA' },
    { sigla: 'MG', descricao: 'SABARA' },
    { sigla: 'MG', descricao: 'SACRAMENTO' },
    { sigla: 'MG', descricao: 'SANTA BARBARA' },
    { sigla: 'MG', descricao: 'SANTA JULIANA' },
    { sigla: 'MG', descricao: 'SANTA LUZIA' },
    { sigla: 'MG', descricao: 'SANTA RITA DO SAPUCAI' },
    { sigla: 'MG', descricao: 'SANTA VITORIA' },
    { sigla: 'MG', descricao: 'SANTANA DA VARGEM' },
    { sigla: 'MG', descricao: 'SANTANA DO PARAISO' },
    { sigla: 'MG', descricao: 'SANTO ANTONIO DO AMPARO' },
    { sigla: 'MG', descricao: 'SAO DOMINGOS DO PRATA' },
    { sigla: 'MG', descricao: 'SAO GERALDO' },
    { sigla: 'MG', descricao: 'SAO GONCALO DO RIO ABAIXO' },
    { sigla: 'MG', descricao: 'SAO GONCALO DO SAPUCAI' },
    { sigla: 'MG', descricao: 'SAO JOAO DA MATA' },
    { sigla: 'MG', descricao: 'SAO JOAO DEL REY' },
    { sigla: 'MG', descricao: 'SAO JOAO DO PARAISO' },
    { sigla: 'MG', descricao: 'SAO JOAQUIM DE BICAS' },
    { sigla: 'MG', descricao: 'SAO JOSE DA BARRA' },
    { sigla: 'MG', descricao: 'SAO JOSE DA LAPA' },
    { sigla: 'MG', descricao: 'SAO JOSE DO GOIABAL' },
    { sigla: 'MG', descricao: 'SAO LOURENCO' },
    { sigla: 'MG', descricao: 'SAO ROMAO' },
    { sigla: 'MG', descricao: 'SAO SEBASTIAO DA BELA VIS' },
    { sigla: 'MG', descricao: 'SAO SEBASTIAO DO OESTE' },
    { sigla: 'MG', descricao: 'SAO SEBASTIAO DO PARAISO' },
    { sigla: 'MG', descricao: 'SAO TOMAS DE AQUINO' },
    { sigla: 'MG', descricao: 'SAO VICENTE DE MINAS' },
    { sigla: 'MG', descricao: 'SAPUCAI-MIRIM' },
    { sigla: 'MG', descricao: 'SARZEDO' },
    { sigla: 'MG', descricao: 'SENADOR AMARAL' },
    { sigla: 'MG', descricao: 'SERRA DO SALITRE' },
    { sigla: 'MG', descricao: 'SERRA DOS AIMORES' },
    { sigla: 'MG', descricao: 'SETE LAGOAS' },
    { sigla: 'MG', descricao: 'SILVIANOPOLIS' },
    { sigla: 'MG', descricao: 'TAIOBEIRAS' },
    { sigla: 'MG', descricao: 'TAPIRA' },
    { sigla: 'MG', descricao: 'TEOFILO OTONI' },
    { sigla: 'MG', descricao: 'TIMOTEO' },
    { sigla: 'MG', descricao: 'TIROS' },
    { sigla: 'MG', descricao: 'TOLEDO' },
    { sigla: 'MG', descricao: 'TRES CORACOES' },
    { sigla: 'MG', descricao: 'TRES PONTAS' },
    { sigla: 'MG', descricao: 'TUPACIGUARA' },
    { sigla: 'MG', descricao: 'UBA' },
    { sigla: 'MG', descricao: 'UBERABA' },
    { sigla: 'MG', descricao: 'UBERLANDIA' },
    { sigla: 'MG', descricao: 'UNAI' },
    { sigla: 'MG', descricao: 'VARGINHA' },
    { sigla: 'MG', descricao: 'VAZANTE' },
    { sigla: 'MG', descricao: 'VERDELANDIA' },
    { sigla: 'MG', descricao: 'VERISSIMO' },
    { sigla: 'MG', descricao: 'VESPASIANO' },
    { sigla: 'MG', descricao: 'VICOSA' },
    { sigla: 'MG', descricao: 'VIRGINIA' },
    { sigla: 'MG', descricao: 'VISCONDE DO RIO BRANCO' },
    { sigla: 'MS', descricao: 'AGUA CLARA' },
    { sigla: 'MS', descricao: 'ALCINOPOLIS' },
    { sigla: 'MS', descricao: 'ANAURILANDIA' },
    { sigla: 'MS', descricao: 'ANGELICA' },
    { sigla: 'MS', descricao: 'APARECIDA DO TABOADO' },
    { sigla: 'MS', descricao: 'BATAGUASSU' },
    { sigla: 'MS', descricao: 'BATAYPORA' },
    { sigla: 'MS', descricao: 'BRASILANDIA' },
    { sigla: 'MS', descricao: 'CAARAPO' },
    { sigla: 'MS', descricao: 'CAMPO GRANDE' },
    { sigla: 'MS', descricao: 'CASSILANDIA' },
    { sigla: 'MS', descricao: 'CHAPADAO DO SUL' },
    { sigla: 'MS', descricao: 'CORUMBA' },
    { sigla: 'MS', descricao: 'COSTA RICA' },
    { sigla: 'MS', descricao: 'DEODAPOLIS' },
    { sigla: 'MS', descricao: 'DOURADOS' },
    { sigla: 'MS', descricao: 'FATIMA DO SUL' },
    { sigla: 'MS', descricao: 'INOCENCIA' },
    { sigla: 'MS', descricao: 'ITAQUIRAI' },
    { sigla: 'MS', descricao: 'IVINHEMA' },
    { sigla: 'MS', descricao: 'LADARIO' },
    { sigla: 'MS', descricao: 'MARACAJU' },
    { sigla: 'MS', descricao: 'MIRANDA' },
    { sigla: 'MS', descricao: 'NAVIRAI' },
    { sigla: 'MS', descricao: 'NOVA ALVORADA DO SUL' },
    { sigla: 'MS', descricao: 'NOVA ANDRADINA' },
    { sigla: 'MS', descricao: 'NOVA UBIRATA' },
    { sigla: 'MS', descricao: 'PARANAIBA' },
    { sigla: 'MS', descricao: 'PONTA PORA' },
    { sigla: 'MS', descricao: 'PORTO MURTINHO' },
    { sigla: 'MS', descricao: 'RIBAS DO RIO PARDO' },
    { sigla: 'MS', descricao: 'RIO BRILHANTE' },
    { sigla: 'MS', descricao: 'RIO VERDE DE MATO GROSSO' },
    { sigla: 'MS', descricao: 'ROCHEDO' },
    { sigla: 'MS', descricao: 'SIDROLANDIA' },
    { sigla: 'MS', descricao: 'SONORA' },
    { sigla: 'MS', descricao: 'TAQUARUSSU' },
    { sigla: 'MS', descricao: 'TRES LAGOAS' },
    { sigla: 'MS', descricao: 'VICENTINA' },
    { sigla: 'MT', descricao: 'AGUA BOA' },
    { sigla: 'MT', descricao: 'ALTO ARAGUAIA' },
    { sigla: 'MT', descricao: 'ALTO BOA VISTA' },
    { sigla: 'MT', descricao: 'ALTO TAQUARI' },
    { sigla: 'MT', descricao: 'BARAO DE MELGACO' },
    { sigla: 'MT', descricao: 'BARRA DO BUGRES' },
    { sigla: 'MT', descricao: 'BARRA DO GARCAS' },
    { sigla: 'MT', descricao: 'CAMPO NOVO DO PARECIS' },
    { sigla: 'MT', descricao: 'CAMPO VERDE' },
    { sigla: 'MT', descricao: 'CAMPOS DE JULIO' },
    { sigla: 'MT', descricao: 'CANARANA' },
    { sigla: 'MT', descricao: 'COCALINHO' },
    { sigla: 'MT', descricao: 'COMODORO' },
    { sigla: 'MT', descricao: 'CONFRESA' },
    { sigla: 'MT', descricao: 'CUIABA' },
    { sigla: 'MT', descricao: 'DIAMANTINO' },
    { sigla: 'MT', descricao: 'GUARANTA DO NORTE' },
    { sigla: 'MT', descricao: 'JACIARA' },
    { sigla: 'MT', descricao: 'JURUENA' },
    { sigla: 'MT', descricao: 'JUSCIMEIRA' },
    { sigla: 'MT', descricao: 'LUCAS DO RIO VERDE' },
    { sigla: 'MT', descricao: 'LUCIARA' },
    { sigla: 'MT', descricao: 'MATO GROSSO' },
    { sigla: 'MT', descricao: `MIRASSOL D'OESTE` },
    { sigla: 'MT', descricao: 'NOVA BANDEIRANTES' },
    { sigla: 'MT', descricao: 'NOVA MARILANDIA' },
    { sigla: 'MT', descricao: 'NOVA MUTUM' },
    { sigla: 'MT', descricao: 'NOVA OLIMPIA' },
    { sigla: 'MT', descricao: 'PARANAITA' },
    { sigla: 'MT', descricao: 'PEDRA PRETA' },
    { sigla: 'MT', descricao: 'PORTO DOS GAUCHOS' },
    { sigla: 'MT', descricao: 'PRIMAVERA DO LESTE' },
    { sigla: 'MT', descricao: 'RIBEIRAO CASCALHEIRA' },
    { sigla: 'MT', descricao: 'RONDONOPOLIS' },
    { sigla: 'MT', descricao: 'ROSARIO OESTE' },
    { sigla: 'MT', descricao: 'SANTO ANTONIO DO LEVERGER' },
    { sigla: 'MT', descricao: 'SAO FELIX DO ARAGUAIA' },
    { sigla: 'MT', descricao: 'SAO JOSE DO RIO CLARO' },
    { sigla: 'MT', descricao: 'SAPEZAL' },
    { sigla: 'MT', descricao: 'SINOP' },
    { sigla: 'MT', descricao: 'SORRISO' },
    { sigla: 'MT', descricao: 'TANGARA DA SERRA' },
    { sigla: 'MT', descricao: 'TORIXOREU' },
    { sigla: 'MT', descricao: 'VARZEA GRANDE' },
    { sigla: 'PA', descricao: 'AGUA AZUL DO NORTE' },
    { sigla: 'PA', descricao: 'ALTAMIRA' },
    { sigla: 'PA', descricao: 'ANANINDEUA' },
    { sigla: 'PA', descricao: 'BELEM' },
    { sigla: 'PA', descricao: 'BENEVIDES' },
    { sigla: 'PA', descricao: 'CANAA DOS CARAJAS' },
    { sigla: 'PA', descricao: 'CASTANHAL' },
    { sigla: 'PA', descricao: 'CONCEICAO DO ARAGUAIA' },
    { sigla: 'PA', descricao: 'ITAITUBA' },
    { sigla: 'PA', descricao: 'JURUTI' },
    { sigla: 'PA', descricao: 'MARABA' },
    { sigla: 'PA', descricao: 'MARITUBA' },
    { sigla: 'PA', descricao: 'MEDICILANDIA' },
    { sigla: 'PA', descricao: 'NOVO PROGRESSO' },
    { sigla: 'PA', descricao: 'OURILANDIA DO NORTE' },
    { sigla: 'PA', descricao: 'PARAGOMINAS' },
    { sigla: 'PA', descricao: 'PARAUAPEBAS' },
    { sigla: 'PA', descricao: 'REDENCAO' },
    { sigla: 'PA', descricao: 'SANTANA DO ARAGUAIA' },
    { sigla: 'PA', descricao: 'SANTAREM' },
    { sigla: 'PA', descricao: 'SAO FELIX DO XINGU' },
    { sigla: 'PA', descricao: 'TRAIRAO' },
    { sigla: 'PA', descricao: 'TUCUMA' },
    { sigla: 'PA', descricao: 'TUCURUI' },
    { sigla: 'PA', descricao: 'ULIANOPOLIS' },
    { sigla: 'PA', descricao: 'XINGUARA' },
    { sigla: 'PB', descricao: 'CABEDELO' },
    { sigla: 'PB', descricao: 'CAJAZEIRAS' },
    { sigla: 'PB', descricao: 'CAMPINA GRANDE' },
    { sigla: 'PB', descricao: 'CATINGUEIRA' },
    { sigla: 'PB', descricao: 'CONDE' },
    { sigla: 'PB', descricao: 'CUITE' },
    { sigla: 'PB', descricao: 'ESPERANCA' },
    { sigla: 'PB', descricao: 'JOAO PESSOA' },
    { sigla: 'PB', descricao: 'PEDRAS DE FOGO' },
    { sigla: 'PB', descricao: 'QUEIMADAS' },
    { sigla: 'PB', descricao: 'REMIGIO' },
    { sigla: 'PB', descricao: 'SANTA RITA' },
    { sigla: 'PE', descricao: 'ARARIPINA' },
    { sigla: 'PE', descricao: 'ARCOVERDE' },
    { sigla: 'PE', descricao: 'BELO JARDIM' },
    { sigla: 'PE', descricao: 'CABO DE SANTO AGOSTINHO' },
    { sigla: 'PE', descricao: 'CABROBO' },
    { sigla: 'PE', descricao: 'CAMARAGIBE' },
    { sigla: 'PE', descricao: 'CARPINA' },
    { sigla: 'PE', descricao: 'CARUARU' },
    { sigla: 'PE', descricao: 'CORTES' },
    { sigla: 'PE', descricao: 'FLORESTA' },
    { sigla: 'PE', descricao: 'GARANHUNS' },
    { sigla: 'PE', descricao: 'GOIANA' },
    { sigla: 'PE', descricao: 'IGARASSU' },
    { sigla: 'PE', descricao: 'IPOJUCA' },
    { sigla: 'PE', descricao: 'ITAPISSUMA' },
    { sigla: 'PE', descricao: 'JABOATAO DOS GUARARAPES' },
    { sigla: 'PE', descricao: 'MORENO' },
    { sigla: 'PE', descricao: 'OLINDA' },
    { sigla: 'PE', descricao: 'PAULISTA' },
    { sigla: 'PE', descricao: 'PETROLINA' },
    { sigla: 'PE', descricao: 'RECIFE' },
    { sigla: 'PE', descricao: 'RIO FORMOSO' },
    { sigla: 'PE', descricao: 'SAO BENTO DO UNA' },
    { sigla: 'PI', descricao: 'BURITI DOS MONTES' },
    { sigla: 'PI', descricao: 'ITAUEIRA' },
    { sigla: 'PI', descricao: 'PICOS' },
    { sigla: 'PI', descricao: 'SAO GONCALO DO GURGUEIA' },
    { sigla: 'PI', descricao: 'TERESINA' },
    { sigla: 'PI', descricao: 'URUCUI' },
    { sigla: 'PR', descricao: 'ADRIANOPOLIS' },
    { sigla: 'PR', descricao: 'ALMIRANTE TAMANDARE' },
    { sigla: 'PR', descricao: 'ALTAMIRA DO PARANA' },
    { sigla: 'PR', descricao: 'ALTO PARANA' },
    { sigla: 'PR', descricao: 'AMAPORA' },
    { sigla: 'PR', descricao: 'ANDIRA' },
    { sigla: 'PR', descricao: 'APUCARANA' },
    { sigla: 'PR', descricao: 'ARAPONGAS' },
    { sigla: 'PR', descricao: 'ARAPOTI' },
    { sigla: 'PR', descricao: 'ARAPUA' },
    { sigla: 'PR', descricao: 'ARARUNA' },
    { sigla: 'PR', descricao: 'ARAUCARIA' },
    { sigla: 'PR', descricao: 'ASSAI' },
    { sigla: 'PR', descricao: 'ASSIS CHATEAUBRIAND' },
    { sigla: 'PR', descricao: 'ASTORGA' },
    { sigla: 'PR', descricao: 'BALSA NOVA' },
    { sigla: 'PR', descricao: 'BANDEIRANTES' },
    { sigla: 'PR', descricao: 'BARBOSA FERRAZ' },
    { sigla: 'PR', descricao: 'BELA VISTA DO PARAISO' },
    { sigla: 'PR', descricao: 'BOA VISTA DA APARECIDA' },
    { sigla: 'PR', descricao: 'BOCAIUVA DO SUL' },
    { sigla: 'PR', descricao: 'CAFELANDIA' },
    { sigla: 'PR', descricao: 'CAMBARA' },
    { sigla: 'PR', descricao: 'CAMBE' },
    { sigla: 'PR', descricao: 'CAMBIRA' },
    { sigla: 'PR', descricao: 'CAMPINA GRANDE DO SUL' },
    { sigla: 'PR', descricao: 'CAMPO LARGO' },
    { sigla: 'PR', descricao: 'CAMPO MAGRO' },
    { sigla: 'PR', descricao: 'CAMPO MOURAO' },
    { sigla: 'PR', descricao: 'CANDIDO DE ABREU' },
    { sigla: 'PR', descricao: 'CANDOI' },
    { sigla: 'PR', descricao: 'CANTAGALO' },
    { sigla: 'PR', descricao: 'CAPITAO LEONIDAS MARQUES' },
    { sigla: 'PR', descricao: 'CARAMBEI' },
    { sigla: 'PR', descricao: 'CARLOPOLIS' },
    { sigla: 'PR', descricao: 'CASCAVEL' },
    { sigla: 'PR', descricao: 'CASTRO' },
    { sigla: 'PR', descricao: 'CEU AZUL' },
    { sigla: 'PR', descricao: 'CHOPINZINHO' },
    { sigla: 'PR', descricao: 'CIANORTE' },
    { sigla: 'PR', descricao: 'CIDADE GAUCHA' },
    { sigla: 'PR', descricao: 'COLOMBO' },
    { sigla: 'PR', descricao: 'COLORADO' },
    { sigla: 'PR', descricao: 'CONGONHINHAS' },
    { sigla: 'PR', descricao: 'CONSELHEIRO MAIRINCK' },
    { sigla: 'PR', descricao: 'CONTENDA' },
    { sigla: 'PR', descricao: 'CORBELIA' },
    { sigla: 'PR', descricao: 'CORNELIO PROCOPIO' },
    { sigla: 'PR', descricao: 'CORONEL DOMINGOS SOARES' },
    { sigla: 'PR', descricao: 'CORONEL VIVIDA' },
    { sigla: 'PR', descricao: 'CRUZEIRO DO OESTE' },
    { sigla: 'PR', descricao: 'CURITIBA' },
    { sigla: 'PR', descricao: 'CURIUVA' },
    { sigla: 'PR', descricao: 'DOIS VIZINHOS' },
    { sigla: 'PR', descricao: 'DOURADINA' },
    { sigla: 'PR', descricao: 'DOUTOR CAMARGO' },
    { sigla: 'PR', descricao: 'ENEAS MARQUES' },
    { sigla: 'PR', descricao: 'ENGENHEIRO BELTRAO' },
    { sigla: 'PR', descricao: 'ENTRE RIOS DO OESTE' },
    { sigla: 'PR', descricao: 'FAROL' },
    { sigla: 'PR', descricao: 'FAXINAL' },
    { sigla: 'PR', descricao: 'FAZENDA RIO GRANDE' },
    { sigla: 'PR', descricao: 'FLORESTA' },
    { sigla: 'PR', descricao: 'FLORESTOPOLIS' },
    { sigla: 'PR', descricao: 'FOZ DO IGUACU' },
    { sigla: 'PR', descricao: 'FRANCISCO BELTRAO' },
    { sigla: 'PR', descricao: 'GUAIRA' },
    { sigla: 'PR', descricao: 'GUAPIRAMA' },
    { sigla: 'PR', descricao: 'GUARAPUAVA' },
    { sigla: 'PR', descricao: 'GUARATUBA' },
    { sigla: 'PR', descricao: 'IBIPORA' },
    { sigla: 'PR', descricao: 'IMBITUVA' },
    { sigla: 'PR', descricao: 'IPIRANGA' },
    { sigla: 'PR', descricao: 'IRATI' },
    { sigla: 'PR', descricao: 'ITAMBE' },
    { sigla: 'PR', descricao: 'IVAI' },
    { sigla: 'PR', descricao: 'IVAIPORA' },
    { sigla: 'PR', descricao: 'IVATE' },
    { sigla: 'PR', descricao: 'JACAREZINHO' },
    { sigla: 'PR', descricao: 'JAGUAPITÃ' },
    { sigla: 'PR', descricao: 'JAGUARIAIVA' },
    { sigla: 'PR', descricao: 'JANDAIA DO SUL' },
    { sigla: 'PR', descricao: 'JAPURA' },
    { sigla: 'PR', descricao: 'JARDIM ALEGRE' },
    { sigla: 'PR', descricao: 'JATAIZINHO' },
    { sigla: 'PR', descricao: 'JESUITAS' },
    { sigla: 'PR', descricao: 'JOAQUIM TAVORA' },
    { sigla: 'PR', descricao: 'JUNDIAI DO SUL' },
    { sigla: 'PR', descricao: 'JURANDA' },
    { sigla: 'PR', descricao: 'JUSSARA' },
    { sigla: 'PR', descricao: 'LAPA' },
    { sigla: 'PR', descricao: 'LARANJEIRAS DO SUL' },
    { sigla: 'PR', descricao: 'LEOPOLIS' },
    { sigla: 'PR', descricao: 'LINDOESTE' },
    { sigla: 'PR', descricao: 'LOANDA' },
    { sigla: 'PR', descricao: 'LONDRINA' },
    { sigla: 'PR', descricao: 'LUIZIANA' },
    { sigla: 'PR', descricao: 'LUNARDELLI' },
    { sigla: 'PR', descricao: 'LUPIONOPOLIS' },
    { sigla: 'PR', descricao: 'MAMBORE' },
    { sigla: 'PR', descricao: 'MANDAGUACU' },
    { sigla: 'PR', descricao: 'MANDAGUARI' },
    { sigla: 'PR', descricao: 'MANDIRITUBA' },
    { sigla: 'PR', descricao: 'MANGUEIRINHA' },
    { sigla: 'PR', descricao: 'MANOEL RIBAS' },
    { sigla: 'PR', descricao: 'MARECHAL CANDIDO RONDON' },
    { sigla: 'PR', descricao: 'MARIALVA' },
    { sigla: 'PR', descricao: 'MARILANDIA DO SUL' },
    { sigla: 'PR', descricao: 'MARINGA' },
    { sigla: 'PR', descricao: 'MARMELEIRO' },
    { sigla: 'PR', descricao: 'MARUMBI' },
    { sigla: 'PR', descricao: 'MATELANDIA' },
    { sigla: 'PR', descricao: 'MEDIANEIRA' },
    { sigla: 'PR', descricao: 'MOREIRA SALES' },
    { sigla: 'PR', descricao: 'MORRETES' },
    { sigla: 'PR', descricao: 'NOVA AMERICA DA COLINA' },
    { sigla: 'PR', descricao: 'NOVA ESPERANCA' },
    { sigla: 'PR', descricao: 'NOVA LONDRINA' },
    { sigla: 'PR', descricao: 'NOVA SANTA ROSA' },
    { sigla: 'PR', descricao: 'NOVA TEBAS' },
    { sigla: 'PR', descricao: 'ORTIGUEIRA' },
    { sigla: 'PR', descricao: 'PAICANDU' },
    { sigla: 'PR', descricao: 'PALMAS' },
    { sigla: 'PR', descricao: 'PALMEIRA' },
    { sigla: 'PR', descricao: 'PALOTINA' },
    { sigla: 'PR', descricao: 'PARANACITY' },
    { sigla: 'PR', descricao: 'PARANAGUA' },
    { sigla: 'PR', descricao: 'PARANAPOEMA' },
    { sigla: 'PR', descricao: 'PARANAVAI' },
    { sigla: 'PR', descricao: 'PATO BRAGADO' },
    { sigla: 'PR', descricao: 'PATO BRANCO' },
    { sigla: 'PR', descricao: 'PAULA FREITAS' },
    { sigla: 'PR', descricao: 'PAULO FRONTIN' },
    { sigla: 'PR', descricao: 'PIEN' },
    { sigla: 'PR', descricao: 'PINHAIS' },
    { sigla: 'PR', descricao: 'PINHALAO' },
    { sigla: 'PR', descricao: 'PINHAO' },
    { sigla: 'PR', descricao: 'PIRAI DO SUL' },
    { sigla: 'PR', descricao: 'PIRAQUARA' },
    { sigla: 'PR', descricao: 'PITANGA' },
    { sigla: 'PR', descricao: 'PLANALTINA DO PARANA' },
    { sigla: 'PR', descricao: 'PONTA GROSSA' },
    { sigla: 'PR', descricao: 'PONTAL DO PARANA' },
    { sigla: 'PR', descricao: 'PORECATU' },
    { sigla: 'PR', descricao: 'PRESIDENTE CASTELO BRANCO' },
    { sigla: 'PR', descricao: 'PRIMEIRO DE MAIO' },
    { sigla: 'PR', descricao: 'PRUDENTOPOLIS' },
    { sigla: 'PR', descricao: 'QUATIGUA' },
    { sigla: 'PR', descricao: 'QUATRO BARRAS' },
    { sigla: 'PR', descricao: 'QUATRO PONTES' },
    { sigla: 'PR', descricao: 'QUINTA DO SOL' },
    { sigla: 'PR', descricao: 'REALEZA' },
    { sigla: 'PR', descricao: 'RIBEIRÃO DO PINHAL' },
    { sigla: 'PR', descricao: 'RIO NEGRO' },
    { sigla: 'PR', descricao: 'ROLANDIA' },
    { sigla: 'PR', descricao: 'RONDON' },
    { sigla: 'PR', descricao: 'SABAUDIA' },
    { sigla: 'PR', descricao: 'SALTO DO ITARARE' },
    { sigla: 'PR', descricao: 'SALTO DO LONTRA' },
    { sigla: 'PR', descricao: 'SANTA HELENA' },
    { sigla: 'PR', descricao: 'SANTA ISABEL DO IVAI' },
    { sigla: 'PR', descricao: 'SANTA MARIANA' },
    { sigla: 'PR', descricao: 'SANTA TEREZA DO OESTE' },
    { sigla: 'PR', descricao: 'SANTA TEREZINHA DE ITAIPU' },
    { sigla: 'PR', descricao: 'SANTANA DO ITARARE' },
    { sigla: 'PR', descricao: 'SANTO ANTONIO DA PLATINA' },
    { sigla: 'PR', descricao: 'SANTO ANTONIO DO PARAISO' },
    { sigla: 'PR', descricao: 'SANTO INACIO' },
    { sigla: 'PR', descricao: 'SAO JERORIMO DA SERRA' },
    { sigla: 'PR', descricao: 'SÃO JOÃO' },
    { sigla: 'PR', descricao: 'SAO JOAO DO IVAI' },
    { sigla: 'PR', descricao: 'SAO JORGE D OESTE' },
    { sigla: 'PR', descricao: 'SÃO JORGE DO PATROCINIO' },
    { sigla: 'PR', descricao: 'SAO JOSE DOS PINHAIS' },
    { sigla: 'PR', descricao: 'SAO MATEUS DO SUL' },
    { sigla: 'PR', descricao: 'SAO MIGUEL DO IGUACU' },
    { sigla: 'PR', descricao: 'SAO PEDRO DO IGUACU' },
    { sigla: 'PR', descricao: 'SAO PEDRO DO IVAI' },
    { sigla: 'PR', descricao: 'SAO TOME' },
    { sigla: 'PR', descricao: 'SARANDI' },
    { sigla: 'PR', descricao: 'SENGES' },
    { sigla: 'PR', descricao: 'SERTANEJA' },
    { sigla: 'PR', descricao: 'SERTANOPOLIS' },
    { sigla: 'PR', descricao: 'SIQUEIRA CAMPOS' },
    { sigla: 'PR', descricao: 'TAMARANA' },
    { sigla: 'PR', descricao: 'TAPEJARA' },
    { sigla: 'PR', descricao: 'TELEMACO BORBA' },
    { sigla: 'PR', descricao: 'TERRA RICA' },
    { sigla: 'PR', descricao: 'TIBAGI' },
    { sigla: 'PR', descricao: 'TIJUCAS DO SUL' },
    { sigla: 'PR', descricao: 'TOLEDO' },
    { sigla: 'PR', descricao: 'TOMAZINA' },
    { sigla: 'PR', descricao: 'UBIRATA' },
    { sigla: 'PR', descricao: 'UMUARAMA' },
    { sigla: 'PR', descricao: 'UNIAO DA VITORIA' },
    { sigla: 'PR', descricao: 'URAI' },
    { sigla: 'PR', descricao: 'VITORINO' },
    { sigla: 'PR', descricao: 'WENCESLAU BRAZ' },
    { sigla: 'RJ', descricao: 'ANGRA DOS REIS' },
    { sigla: 'RJ', descricao: 'APERIBE' },
    { sigla: 'RJ', descricao: 'ARARUAMA' },
    { sigla: 'RJ', descricao: 'AREAL' },
    { sigla: 'RJ', descricao: 'ARMACAO DOS BUZIOS' },
    { sigla: 'RJ', descricao: 'ARRAIL DO CABO' },
    { sigla: 'RJ', descricao: 'BARRA DO PIRAI' },
    { sigla: 'RJ', descricao: 'BARRA MANSA' },
    { sigla: 'RJ', descricao: 'BELFORD ROXO' },
    { sigla: 'RJ', descricao: 'BOM JARDIM' },
    { sigla: 'RJ', descricao: 'BOM JESUS DO ITABAPOANA' },
    { sigla: 'RJ', descricao: 'CABO FRIO' },
    { sigla: 'RJ', descricao: 'CACHOEIRAS DE MACACU' },
    { sigla: 'RJ', descricao: 'CAMBUCI' },
    { sigla: 'RJ', descricao: 'CAMPOS DOS GOYTACAZES' },
    { sigla: 'RJ', descricao: 'CANTAGALO' },
    { sigla: 'RJ', descricao: 'CARAPEBUS' },
    { sigla: 'RJ', descricao: 'CARDOSO MOREIRA' },
    { sigla: 'RJ', descricao: 'CASIMIRO DE ABREU' },
    { sigla: 'RJ', descricao: 'COMENDADOR LEVY GASPARIAN' },
    { sigla: 'RJ', descricao: 'CONCEICAO DE MACABU' },
    { sigla: 'RJ', descricao: 'CORDEIRO' },
    { sigla: 'RJ', descricao: 'DUQUE DE CAXIAS' },
    { sigla: 'RJ', descricao: 'GUAPIMIRIM' },
    { sigla: 'RJ', descricao: 'ITABORAI' },
    { sigla: 'RJ', descricao: 'ITAGUAI' },
    { sigla: 'RJ', descricao: 'ITAPERUNA' },
    { sigla: 'RJ', descricao: 'ITATIAIA' },
    { sigla: 'RJ', descricao: 'JAPERI' },
    { sigla: 'RJ', descricao: 'LAJE DO MUIARE' },
    { sigla: 'RJ', descricao: 'MACAE' },
    { sigla: 'RJ', descricao: 'MAGE' },
    { sigla: 'RJ', descricao: 'MANGARATIBA' },
    { sigla: 'RJ', descricao: 'MARICA' },
    { sigla: 'RJ', descricao: 'MESQUITA' },
    { sigla: 'RJ', descricao: 'MIGUEL PEREIRA' },
    { sigla: 'RJ', descricao: 'NILOPOLIS' },
    { sigla: 'RJ', descricao: 'NITEROI' },
    { sigla: 'RJ', descricao: 'NOVA FRIBURGO' },
    { sigla: 'RJ', descricao: 'NOVA IGUACU' },
    { sigla: 'RJ', descricao: 'PARACAMBI' },
    { sigla: 'RJ', descricao: 'PARAIBA DO SUL' },
    { sigla: 'RJ', descricao: 'PARATY' },
    { sigla: 'RJ', descricao: 'PETROPOLIS' },
    { sigla: 'RJ', descricao: 'PINHEIRAL' },
    { sigla: 'RJ', descricao: 'PIRAI' },
    { sigla: 'RJ', descricao: 'PORTO REAL' },
    { sigla: 'RJ', descricao: 'QUATIS' },
    { sigla: 'RJ', descricao: 'QUEIMADOS' },
    { sigla: 'RJ', descricao: 'RESENDE' },
    { sigla: 'RJ', descricao: 'RIO BONITO' },
    { sigla: 'RJ', descricao: 'RIO DAS FLORES' },
    { sigla: 'RJ', descricao: 'RIO DAS OSTRAS' },
    { sigla: 'RJ', descricao: 'RIO DE JANEIRO' },
    { sigla: 'RJ', descricao: 'S.FRANCISCO DE ITABAPOANA' },
    { sigla: 'RJ', descricao: 'SANTO ANTONIO DE PADUA' },
    { sigla: 'RJ', descricao: 'SAO GONCALO' },
    { sigla: 'RJ', descricao: 'SAO JOAO DA BARRA' },
    { sigla: 'RJ', descricao: 'SAO JOAO DE MERITI' },
    { sigla: 'RJ', descricao: 'SAO PEDRO DA ALDEIA' },
    { sigla: 'RJ', descricao: 'SAPUCAIA' },
    { sigla: 'RJ', descricao: 'SAQUAREMA' },
    { sigla: 'RJ', descricao: 'SEROPEDICA' },
    { sigla: 'RJ', descricao: 'SILVA JARDIM' },
    { sigla: 'RJ', descricao: 'TANGUA' },
    { sigla: 'RJ', descricao: 'TERESOPOLIS' },
    { sigla: 'RJ', descricao: 'TRES RIOS' },
    { sigla: 'RJ', descricao: 'VALENCA' },
    { sigla: 'RJ', descricao: 'VASSOURAS' },
    { sigla: 'RJ', descricao: 'VOLTA REDONDA' },
    { sigla: 'RN', descricao: 'ALTO DO RODRIGUES' },
    { sigla: 'RN', descricao: 'ARES' },
    { sigla: 'RN', descricao: 'BAIA FORMOSA' },
    { sigla: 'RN', descricao: 'ESPIRITO SANTO' },
    { sigla: 'RN', descricao: 'MOSSORO' },
    { sigla: 'RN', descricao: 'NATAL' },
    { sigla: 'RN', descricao: 'PARAZINHO' },
    { sigla: 'RN', descricao: 'PARNAMIRIM' },
    { sigla: 'RN', descricao: 'PEDRA GRANDE' },
    { sigla: 'RO', descricao: 'ARIQUEMES' },
    { sigla: 'RO', descricao: 'CACOAL' },
    { sigla: 'RO', descricao: 'CHUPINGUAIA' },
    { sigla: 'RO', descricao: 'COLORADO DO OESTE' },
    { sigla: 'RO', descricao: 'JARU' },
    { sigla: 'RO', descricao: 'PIMENTA BUENO' },
    { sigla: 'RO', descricao: 'PORTO VELHO' },
    { sigla: 'RO', descricao: 'ROLIM DE MOURA' },
    { sigla: 'RO', descricao: 'VILHENA' },
    { sigla: 'RR', descricao: 'BOA VISTA' },
    { sigla: 'RR', descricao: 'BONFIM' },
    { sigla: 'RS', descricao: 'ALVORADA' },
    { sigla: 'RS', descricao: 'ARROIO DOS RATOS' },
    { sigla: 'RS', descricao: 'BARAO' },
    { sigla: 'RS', descricao: 'BARRACAO' },
    { sigla: 'RS', descricao: 'BARROS CASSAL' },
    { sigla: 'RS', descricao: 'BENTO GONCALVES' },
    { sigla: 'RS', descricao: 'BOM JESUS' },
    { sigla: 'RS', descricao: 'CACHOEIRA DO SUL' },
    { sigla: 'RS', descricao: 'CACHOEIRINHA' },
    { sigla: 'RS', descricao: 'CAIBATE' },
    { sigla: 'RS', descricao: 'CAMAQUÃ' },
    { sigla: 'RS', descricao: 'CAMBARA DO SUL' },
    { sigla: 'RS', descricao: 'CAMPO BOM' },
    { sigla: 'RS', descricao: 'CANDIDO GODOI' },
    { sigla: 'RS', descricao: 'CANDIOTA' },
    { sigla: 'RS', descricao: 'CANELA' },
    { sigla: 'RS', descricao: 'CANOAS' },
    { sigla: 'RS', descricao: 'CARAZINHO' },
    { sigla: 'RS', descricao: 'CARLOS BARBOSA' },
    { sigla: 'RS', descricao: 'CASCA' },
    { sigla: 'RS', descricao: 'CAXIAS DO SUL' },
    { sigla: 'RS', descricao: 'CERRO LARGO' },
    { sigla: 'RS', descricao: 'COXILHA' },
    { sigla: 'RS', descricao: 'CRUZ ALTA' },
    { sigla: 'RS', descricao: 'ELDORADO DO SUL' },
    { sigla: 'RS', descricao: 'ERECHIM' },
    { sigla: 'RS', descricao: 'ESPUMOSO' },
    { sigla: 'RS', descricao: 'ESTANCIA VELHA' },
    { sigla: 'RS', descricao: 'ESTEIO' },
    { sigla: 'RS', descricao: 'ESTRELA' },
    { sigla: 'RS', descricao: 'FARROUPILHA' },
    { sigla: 'RS', descricao: 'FELIZ' },
    { sigla: 'RS', descricao: 'FLORES DA CUNHA' },
    { sigla: 'RS', descricao: 'GARIBALDI' },
    { sigla: 'RS', descricao: 'GETULIO VARGAS' },
    { sigla: 'RS', descricao: 'GRAMADO' },
    { sigla: 'RS', descricao: 'GRAVATAI' },
    { sigla: 'RS', descricao: 'GUAIBA' },
    { sigla: 'RS', descricao: 'GUAPORE' },
    { sigla: 'RS', descricao: 'HORIZONTINA' },
    { sigla: 'RS', descricao: 'IBIRAIARAS' },
    { sigla: 'RS', descricao: 'IBIRUBA' },
    { sigla: 'RS', descricao: 'IMIGRANTE' },
    { sigla: 'RS', descricao: 'JÚLIO DE CASTILHOS' },
    { sigla: 'RS', descricao: 'LAGOA VERMELHA' },
    { sigla: 'RS', descricao: 'LAJEADO' },
    { sigla: 'RS', descricao: 'MARAU' },
    { sigla: 'RS', descricao: 'MATO LEITAO' },
    { sigla: 'RS', descricao: 'MAXIMILIANO DE ALMEIDA' },
    { sigla: 'RS', descricao: 'MONTENEGRO' },
    { sigla: 'RS', descricao: 'MORRO REUTER' },
    { sigla: 'RS', descricao: 'NOVA BASSANO' },
    { sigla: 'RS', descricao: 'NOVA HARTZ' },
    { sigla: 'RS', descricao: 'NOVA SANTA RITA' },
    { sigla: 'RS', descricao: 'NOVO HAMBURGO' },
    { sigla: 'RS', descricao: 'PANAMBI' },
    { sigla: 'RS', descricao: 'PAROBE' },
    { sigla: 'RS', descricao: 'PASSO FUNDO' },
    { sigla: 'RS', descricao: 'PELOTAS' },
    { sigla: 'RS', descricao: 'PORTO ALEGRE' },
    { sigla: 'RS', descricao: 'RIO GRANDE' },
    { sigla: 'RS', descricao: 'RIOZINHO' },
    { sigla: 'RS', descricao: 'RODEIO BONITO' },
    { sigla: 'RS', descricao: 'ROSARIO DO SUL' },
    { sigla: 'RS', descricao: 'SANTA CRUZ DO SUL' },
    { sigla: 'RS', descricao: 'SANTA MARIA' },
    { sigla: 'RS', descricao: 'SAO BORJA' },
    { sigla: 'RS', descricao: 'SAO LEOPOLDO' },
    { sigla: 'RS', descricao: 'SAO MARCOS' },
    { sigla: 'RS', descricao: 'SAO PEDRO DA SERRA' },
    { sigla: 'RS', descricao: 'SAO SEBASTIAO DO CAI' },
    { sigla: 'RS', descricao: 'SAPIRANGA' },
    { sigla: 'RS', descricao: 'SAPUCAIA DO SUL' },
    { sigla: 'RS', descricao: 'SARANDI' },
    { sigla: 'RS', descricao: 'SOLEDADE' },
    { sigla: 'RS', descricao: 'TABAI' },
    { sigla: 'RS', descricao: 'TAPERA' },
    { sigla: 'RS', descricao: 'TAQUARA' },
    { sigla: 'RS', descricao: 'TUPANCIRETA' },
    { sigla: 'RS', descricao: 'VACARIA' },
    { sigla: 'RS', descricao: 'VENANCIO AIRES' },
    { sigla: 'SC', descricao: 'AGROLANDIA' },
    { sigla: 'SC', descricao: 'AGUAS DE CHAPECO' },
    { sigla: 'SC', descricao: 'AGUAS FRIAS' },
    { sigla: 'SC', descricao: 'ARAQUARI' },
    { sigla: 'SC', descricao: 'ARARANGUA' },
    { sigla: 'SC', descricao: 'ARVOREDO' },
    { sigla: 'SC', descricao: 'ASCURRA' },
    { sigla: 'SC', descricao: 'ATALANTA' },
    { sigla: 'SC', descricao: 'AURORA' },
    { sigla: 'SC', descricao: 'BALNEARIO BARRA DO SUL' },
    { sigla: 'SC', descricao: 'BALNEARIO CAMBORIU' },
    { sigla: 'SC', descricao: 'BALNEARIO PICARRAS' },
    { sigla: 'SC', descricao: 'BARRA VELHA' },
    { sigla: 'SC', descricao: 'BIGUACU' },
    { sigla: 'SC', descricao: 'BLUMENAU' },
    { sigla: 'SC', descricao: 'BOTUVERA' },
    { sigla: 'SC', descricao: 'BRACO DO NORTE' },
    { sigla: 'SC', descricao: 'BRACO DO TROMBUDO' },
    { sigla: 'SC', descricao: 'BRUSQUE' },
    { sigla: 'SC', descricao: 'CACADOR' },
    { sigla: 'SC', descricao: 'CAIBI' },
    { sigla: 'SC', descricao: 'CAMBORIU' },
    { sigla: 'SC', descricao: 'CAMPO ALEGRE' },
    { sigla: 'SC', descricao: 'CAMPOS NOVOS' },
    { sigla: 'SC', descricao: 'CANOINHAS' },
    { sigla: 'SC', descricao: 'CAPINZAL' },
    { sigla: 'SC', descricao: 'CAPIVARI DE BAIXO' },
    { sigla: 'SC', descricao: 'CHAPECO' },
    { sigla: 'SC', descricao: 'COCAL DO SUL' },
    { sigla: 'SC', descricao: 'CONCORDIA' },
    { sigla: 'SC', descricao: 'CORDILHEIRA ALTA' },
    { sigla: 'SC', descricao: 'CORONEL FREITAS' },
    { sigla: 'SC', descricao: 'CORREIA PINTO' },
    { sigla: 'SC', descricao: 'CORUPA' },
    { sigla: 'SC', descricao: 'CRICIUMA' },
    { sigla: 'SC', descricao: 'ERVAL VELHO' },
    { sigla: 'SC', descricao: 'FAXINAL DOS GUEDES' },
    { sigla: 'SC', descricao: 'FLORIANOPOLIS' },
    { sigla: 'SC', descricao: 'FORQUILINHA' },
    { sigla: 'SC', descricao: 'FRAIBURGO' },
    { sigla: 'SC', descricao: 'GARUVA' },
    { sigla: 'SC', descricao: 'GASPAR' },
    { sigla: 'SC', descricao: 'GUABIRUBA' },
    { sigla: 'SC', descricao: 'GUARAMIRIM' },
    { sigla: 'SC', descricao: 'HERVAL D OESTE' },
    { sigla: 'SC', descricao: 'IBIRAMA' },
    { sigla: 'SC', descricao: 'ICARA' },
    { sigla: 'SC', descricao: 'ILHOTA' },
    { sigla: 'SC', descricao: 'IMBITUBA' },
    { sigla: 'SC', descricao: 'INDAIAL' },
    { sigla: 'SC', descricao: 'IRANI' },
    { sigla: 'SC', descricao: 'ITAJAI' },
    { sigla: 'SC', descricao: 'ITAPEMA' },
    { sigla: 'SC', descricao: 'ITAPIRANGA' },
    { sigla: 'SC', descricao: 'ITUPORANGA' },
    { sigla: 'SC', descricao: 'JAGUARUNA' },
    { sigla: 'SC', descricao: 'JARAGUA DO SUL' },
    { sigla: 'SC', descricao: 'JOACABA' },
    { sigla: 'SC', descricao: 'JOINVILLE' },
    { sigla: 'SC', descricao: 'LAGES' },
    { sigla: 'SC', descricao: 'LAGUNA' },
    { sigla: 'SC', descricao: 'LAURO MULLER' },
    { sigla: 'SC', descricao: 'LONTRAS' },
    { sigla: 'SC', descricao: 'LUZERNA' },
    { sigla: 'SC', descricao: 'MAFRA' },
    { sigla: 'SC', descricao: 'MARACAJA' },
    { sigla: 'SC', descricao: 'MARAVILHA' },
    { sigla: 'SC', descricao: 'MASSARANDUBA' },
    { sigla: 'SC', descricao: 'MELEIRO' },
    { sigla: 'SC', descricao: 'MODELO' },
    { sigla: 'SC', descricao: 'MORRO DA FUMACA' },
    { sigla: 'SC', descricao: 'NAVEGANTES' },
    { sigla: 'SC', descricao: 'NOVA TRENTO' },
    { sigla: 'SC', descricao: 'NOVA VENEZA' },
    { sigla: 'SC', descricao: 'ORLEANS' },
    { sigla: 'SC', descricao: 'OTACILIO COSTA' },
    { sigla: 'SC', descricao: 'OURO' },
    { sigla: 'SC', descricao: 'PALHOCA' },
    { sigla: 'SC', descricao: 'PALMEIRA' },
    { sigla: 'SC', descricao: 'PAULO LOPES' },
    { sigla: 'SC', descricao: 'PEDRAS GRANDES' },
    { sigla: 'SC', descricao: 'PENHA' },
    { sigla: 'SC', descricao: 'PERITIBA' },
    { sigla: 'SC', descricao: 'PINHALZINHO' },
    { sigla: 'SC', descricao: 'POMERODE' },
    { sigla: 'SC', descricao: 'PORTO BELO' },
    { sigla: 'SC', descricao: 'PORTO UNIAO' },
    { sigla: 'SC', descricao: 'POUSO REDONDO' },
    { sigla: 'SC', descricao: 'RIO DO CAMPO' },
    { sigla: 'SC', descricao: 'RIO DO OESTE' },
    { sigla: 'SC', descricao: 'RIO DO SUL' },
    { sigla: 'SC', descricao: 'RIO DOS CEDROS' },
    { sigla: 'SC', descricao: 'RIO NEGRINHO' },
    { sigla: 'SC', descricao: 'RIQUEZA' },
    { sigla: 'SC', descricao: 'RODEIO' },
    { sigla: 'SC', descricao: 'SALETE' },
    { sigla: 'SC', descricao: 'SALTO VELOSO' },
    { sigla: 'SC', descricao: 'SANGAO' },
    { sigla: 'SC', descricao: 'SANTA CECILIA' },
    { sigla: 'SC', descricao: 'SANTO AMARO DA IMPERATRIZ' },
    { sigla: 'SC', descricao: 'SAO BENTO DO SUL' },
    { sigla: 'SC', descricao: 'SAO CARLOS' },
    { sigla: 'SC', descricao: 'SAO DOMINGOS' },
    { sigla: 'SC', descricao: 'SAO FRANCISCO DO SUL' },
    { sigla: 'SC', descricao: 'SAO JOAO DO ITAPERIU' },
    { sigla: 'SC', descricao: 'SÃO JOÃO DO OESTE' },
    { sigla: 'SC', descricao: 'SAO JOSE' },
    { sigla: 'SC', descricao: 'SAO LOURENCO DO OESTE' },
    { sigla: 'SC', descricao: 'SAO MIGUEL DO OESTE' },
    { sigla: 'SC', descricao: 'SCHROEDER' },
    { sigla: 'SC', descricao: 'SEARA' },
    { sigla: 'SC', descricao: 'SIDEROPOLIS' },
    { sigla: 'SC', descricao: 'TAIO' },
    { sigla: 'SC', descricao: 'TIJUCAS' },
    { sigla: 'SC', descricao: 'TIMBO' },
    { sigla: 'SC', descricao: 'TRES BARRAS' },
    { sigla: 'SC', descricao: 'TREZE TILIAS' },
    { sigla: 'SC', descricao: 'TROMBUDO CENTRAL' },
    { sigla: 'SC', descricao: 'TUBARAO' },
    { sigla: 'SC', descricao: 'TURVO' },
    { sigla: 'SC', descricao: 'URUSSANGA' },
    { sigla: 'SC', descricao: 'VARGEM' },
    { sigla: 'SC', descricao: 'VIDEIRA' },
    { sigla: 'SC', descricao: 'XANXERE' },
    { sigla: 'SC', descricao: 'XAVANTINA' },
    { sigla: 'SC', descricao: 'XAXIM' },
    { sigla: 'SE', descricao: 'ARACAJU' },
    { sigla: 'SE', descricao: 'BARRA DOS COQUEIROS' },
    { sigla: 'SE', descricao: 'CAPELA' },
    { sigla: 'SE', descricao: 'ESTANCIA' },
    { sigla: 'SE', descricao: 'INDIAROBA' },
    { sigla: 'SE', descricao: 'LARANJEIRAS' },
    { sigla: 'SE', descricao: 'MARUIM' },
    { sigla: 'SE', descricao: 'NOSSA SENHORA DAS DORES' },
    { sigla: 'SE', descricao: 'NOSSA SENHORA DO SOCORRO' },
    { sigla: 'SP', descricao: 'ADAMANTINA' },
    { sigla: 'SP', descricao: 'ADOLFO' },
    { sigla: 'SP', descricao: 'AGUAI' },
    { sigla: 'SP', descricao: 'AGUAS DA PRATA' },
    { sigla: 'SP', descricao: 'AGUAS DE LINDOIA' },
    { sigla: 'SP', descricao: 'AGUAS DE SANTA BARBARA' },
    { sigla: 'SP', descricao: 'AGUAS DE SAO PEDRO' },
    { sigla: 'SP', descricao: 'AGUDOS' },
    { sigla: 'SP', descricao: 'ALAMBARI' },
    { sigla: 'SP', descricao: 'ALFREDO MARCONDES' },
    { sigla: 'SP', descricao: 'ALTAIR' },
    { sigla: 'SP', descricao: 'ALTINOPOLIS' },
    { sigla: 'SP', descricao: 'ALTO ALEGRE' },
    { sigla: 'SP', descricao: 'ALUMINIO' },
    { sigla: 'SP', descricao: 'ALVARES FLORENCE' },
    { sigla: 'SP', descricao: 'ALVARES MACHADO' },
    { sigla: 'SP', descricao: 'ALVARO DE CARVALHO' },
    { sigla: 'SP', descricao: 'ALVINLANDIA' },
    { sigla: 'SP', descricao: 'AMERICANA' },
    { sigla: 'SP', descricao: 'AMERICO BRASILIENSE' },
    { sigla: 'SP', descricao: 'AMERICO DE CAMPOS' },
    { sigla: 'SP', descricao: 'AMPARO' },
    { sigla: 'SP', descricao: 'ANALANDIA' },
    { sigla: 'SP', descricao: 'ANDRADINA' },
    { sigla: 'SP', descricao: 'ANGATUBA' },
    { sigla: 'SP', descricao: 'ANHEMBI' },
    { sigla: 'SP', descricao: 'ANHUMAS' },
    { sigla: 'SP', descricao: 'APARECIDA' },
    { sigla: 'SP', descricao: 'APARECIDA DO OESTE' },
    { sigla: 'SP', descricao: 'APIAI' },
    { sigla: 'SP', descricao: 'ARACARIGUAMA' },
    { sigla: 'SP', descricao: 'ARACATUBA' },
    { sigla: 'SP', descricao: 'ARACOIABA DA SERRA' },
    { sigla: 'SP', descricao: 'ARAMINA' },
    { sigla: 'SP', descricao: 'ARANDU' },
    { sigla: 'SP', descricao: 'ARAPEI' },
    { sigla: 'SP', descricao: 'ARARAQUARA' },
    { sigla: 'SP', descricao: 'ARARAS' },
    { sigla: 'SP', descricao: 'ARCO IRIS' },
    { sigla: 'SP', descricao: 'AREALVA' },
    { sigla: 'SP', descricao: 'AREIAS' },
    { sigla: 'SP', descricao: 'AREIOPOLIS' },
    { sigla: 'SP', descricao: 'ARIRANHA' },
    { sigla: 'SP', descricao: 'ARTUR NOGUEIRA' },
    { sigla: 'SP', descricao: 'ARUJA' },
    { sigla: 'SP', descricao: 'ASPASIA' },
    { sigla: 'SP', descricao: 'ASSIS' },
    { sigla: 'SP', descricao: 'ATIBAIA' },
    { sigla: 'SP', descricao: 'AURIFLAMA' },
    { sigla: 'SP', descricao: 'AVAI' },
    { sigla: 'SP', descricao: 'AVANHANDAVA' },
    { sigla: 'SP', descricao: 'AVARE' },
    { sigla: 'SP', descricao: 'BADY BASSITT' },
    { sigla: 'SP', descricao: 'BALBINOS' },
    { sigla: 'SP', descricao: 'BALSAMO' },
    { sigla: 'SP', descricao: 'BANANAL' },
    { sigla: 'SP', descricao: 'BARAO DE ANTONINA' },
    { sigla: 'SP', descricao: 'BARBOSA' },
    { sigla: 'SP', descricao: 'BARIRI' },
    { sigla: 'SP', descricao: 'BARRA BONITA' },
    { sigla: 'SP', descricao: 'BARRA DO CHAPEU' },
    { sigla: 'SP', descricao: 'BARRA DO TURVO' },
    { sigla: 'SP', descricao: 'BARRETOS' },
    { sigla: 'SP', descricao: 'BARRINHA' },
    { sigla: 'SP', descricao: 'BARUERI' },
    { sigla: 'SP', descricao: 'BASTOS' },
    { sigla: 'SP', descricao: 'BATATAIS' },
    { sigla: 'SP', descricao: 'BAURU' },
    { sigla: 'SP', descricao: 'BEBEDOURO' },
    { sigla: 'SP', descricao: 'BENTO DE ABREU' },
    { sigla: 'SP', descricao: 'BERNARDINO DE CAMPOS' },
    { sigla: 'SP', descricao: 'BERTIOGA' },
    { sigla: 'SP', descricao: 'BILAC' },
    { sigla: 'SP', descricao: 'BIRIGUI' },
    { sigla: 'SP', descricao: 'BIRITIBA-MIRIM' },
    { sigla: 'SP', descricao: 'BOA ESPERANCA DO SUL' },
    { sigla: 'SP', descricao: 'BOCAINA' },
    { sigla: 'SP', descricao: 'BOFETE' },
    { sigla: 'SP', descricao: 'BOITUVA' },
    { sigla: 'SP', descricao: 'BOM JESUS DOS PERDOES' },
    { sigla: 'SP', descricao: 'BOM SUCESSO DE ITARARE' },
    { sigla: 'SP', descricao: 'BORA' },
    { sigla: 'SP', descricao: 'BORACEIA' },
    { sigla: 'SP', descricao: 'BORBOREMA' },
    { sigla: 'SP', descricao: 'BOREBI' },
    { sigla: 'SP', descricao: 'BOTUCATU' },
    { sigla: 'SP', descricao: 'BRAGANCA PAULISTA' },
    { sigla: 'SP', descricao: 'BRAUNA' },
    { sigla: 'SP', descricao: 'BREJO ALEGRE' },
    { sigla: 'SP', descricao: 'BRODOWSKI' },
    { sigla: 'SP', descricao: 'BROTAS' },
    { sigla: 'SP', descricao: 'BURI' },
    { sigla: 'SP', descricao: 'BURITAMA' },
    { sigla: 'SP', descricao: 'BURITIZAL' },
    { sigla: 'SP', descricao: 'CABRALIA PAULISTA' },
    { sigla: 'SP', descricao: 'CABREUVA' },
    { sigla: 'SP', descricao: 'CACAPAVA' },
    { sigla: 'SP', descricao: 'CACHOEIRA PAULISTA' },
    { sigla: 'SP', descricao: 'CACONDE' },
    { sigla: 'SP', descricao: 'CAFELANDIA' },
    { sigla: 'SP', descricao: 'CAIABU' },
    { sigla: 'SP', descricao: 'CAIEIRAS' },
    { sigla: 'SP', descricao: 'CAIUA' },
    { sigla: 'SP', descricao: 'CAJAMAR' },
    { sigla: 'SP', descricao: 'CAJATI' },
    { sigla: 'SP', descricao: 'CAJOBI' },
    { sigla: 'SP', descricao: 'CAJURU' },
    { sigla: 'SP', descricao: 'CAMPINA DO MONTE ALEGRE' },
    { sigla: 'SP', descricao: 'CAMPINAS' },
    { sigla: 'SP', descricao: 'CAMPO LIMPO PAULISTA' },
    { sigla: 'SP', descricao: 'CAMPOS DO JORDAO' },
    { sigla: 'SP', descricao: 'CAMPOS NOVOS PAULISTA' },
    { sigla: 'SP', descricao: 'CANANEIA' },
    { sigla: 'SP', descricao: 'CANAS' },
    { sigla: 'SP', descricao: 'CANDIDO MOTA' },
    { sigla: 'SP', descricao: 'CANDIDO RODRIGUES' },
    { sigla: 'SP', descricao: 'CANITAR' },
    { sigla: 'SP', descricao: 'CAPAO BONITO' },
    { sigla: 'SP', descricao: 'CAPELA DO ALTO' },
    { sigla: 'SP', descricao: 'CAPIVARI' },
    { sigla: 'SP', descricao: 'CARAGUATATUBA' },
    { sigla: 'SP', descricao: 'CARAPICUIBA' },
    { sigla: 'SP', descricao: 'CARDOSO' },
    { sigla: 'SP', descricao: 'CASA BRANCA' },
    { sigla: 'SP', descricao: 'CASSIA DOS COQUEIROS' },
    { sigla: 'SP', descricao: 'CASTILHO' },
    { sigla: 'SP', descricao: 'CATANDUVA' },
    { sigla: 'SP', descricao: 'CATIGUA' },
    { sigla: 'SP', descricao: 'CEDRAL' },
    { sigla: 'SP', descricao: 'CERQUEIRA CESAR' },
    { sigla: 'SP', descricao: 'CERQUILHO' },
    { sigla: 'SP', descricao: 'CESARIO LANGE' },
    { sigla: 'SP', descricao: 'CHARQUEADA' },
    { sigla: 'SP', descricao: 'CHAVANTES' },
    { sigla: 'SP', descricao: 'CLEMENTINA' },
    { sigla: 'SP', descricao: 'COLINA' },
    { sigla: 'SP', descricao: 'COLOMBIA' },
    { sigla: 'SP', descricao: 'CONCHAL' },
    { sigla: 'SP', descricao: 'CONCHAS' },
    { sigla: 'SP', descricao: 'CORDEIROPOLIS' },
    { sigla: 'SP', descricao: 'COROADOS' },
    { sigla: 'SP', descricao: 'CORONEL MACEDO' },
    { sigla: 'SP', descricao: 'CORUMBATAI' },
    { sigla: 'SP', descricao: 'COSMOPOLIS' },
    { sigla: 'SP', descricao: 'COSMORAMA' },
    { sigla: 'SP', descricao: 'COTIA' },
    { sigla: 'SP', descricao: 'CRAVINHOS' },
    { sigla: 'SP', descricao: 'CRISTAIS PAULISTA' },
    { sigla: 'SP', descricao: 'CRUZALIA' },
    { sigla: 'SP', descricao: 'CRUZEIRO' },
    { sigla: 'SP', descricao: 'CUBATAO' },
    { sigla: 'SP', descricao: 'CUNHA' },
    { sigla: 'SP', descricao: 'DESCALVADO' },
    { sigla: 'SP', descricao: 'DIADEMA' },
    { sigla: 'SP', descricao: 'DIRCE REIS' },
    { sigla: 'SP', descricao: 'DIVINOLANDIA' },
    { sigla: 'SP', descricao: 'DOBRADA' },
    { sigla: 'SP', descricao: 'DOIS CORREGOS' },
    { sigla: 'SP', descricao: 'DOLCINOPOLIS' },
    { sigla: 'SP', descricao: 'DOURADO' },
    { sigla: 'SP', descricao: 'DRACENA' },
    { sigla: 'SP', descricao: 'DUARTINA' },
    { sigla: 'SP', descricao: 'DUMONT' },
    { sigla: 'SP', descricao: 'ECHAPORA' },
    { sigla: 'SP', descricao: 'ELDORADO' },
    { sigla: 'SP', descricao: 'ELIAS FAUSTO' },
    { sigla: 'SP', descricao: 'ELISIARIO' },
    { sigla: 'SP', descricao: 'EMBAUBA' },
    { sigla: 'SP', descricao: 'EMBU DAS ARTES' },
    { sigla: 'SP', descricao: 'EMBU-GUACU' },
    { sigla: 'SP', descricao: 'EMILIANOPOLIS' },
    { sigla: 'SP', descricao: 'ENGENHEIRO COELHO' },
    { sigla: 'SP', descricao: 'ESPIRITO SANTO DO PINHAL' },
    { sigla: 'SP', descricao: 'ESPIRITO SANTO DO TURVO' },
    { sigla: 'SP', descricao: 'ESTIVA GERBI' },
    { sigla: 'SP', descricao: 'ESTRELA DO NORTE' },
    { sigla: 'SP', descricao: 'ESTRELA DO OESTE' },
    { sigla: 'SP', descricao: 'EUCLIDES DA CUNHA PAULIST' },
    { sigla: 'SP', descricao: 'FARTURA' },
    { sigla: 'SP', descricao: 'FERNANDO PRESTES' },
    { sigla: 'SP', descricao: 'FERNANDOPOLIS' },
    { sigla: 'SP', descricao: 'FERNAO' },
    { sigla: 'SP', descricao: 'FERRAZ DE VASCONCELOS' },
    { sigla: 'SP', descricao: 'FLORA RICA' },
    { sigla: 'SP', descricao: 'FLOREAL' },
    { sigla: 'SP', descricao: 'FLORIDA PAULISTA' },
    { sigla: 'SP', descricao: 'FLORINIA' },
    { sigla: 'SP', descricao: 'FRANCA' },
    { sigla: 'SP', descricao: 'FRANCISCO MORATO' },
    { sigla: 'SP', descricao: 'FRANCO DA ROCHA' },
    { sigla: 'SP', descricao: 'GABRIEL MONTEIRO' },
    { sigla: 'SP', descricao: 'GALIA' },
    { sigla: 'SP', descricao: 'GARCA' },
    { sigla: 'SP', descricao: 'GASTAO VIDIGAL' },
    { sigla: 'SP', descricao: 'GAVIAO PEIXOTO' },
    { sigla: 'SP', descricao: 'GENERAL SALGADO' },
    { sigla: 'SP', descricao: 'GETULINA' },
    { sigla: 'SP', descricao: 'GLICERIO' },
    { sigla: 'SP', descricao: 'GUAICARA' },
    { sigla: 'SP', descricao: 'GUAIMBE' },
    { sigla: 'SP', descricao: 'GUAIRA' },
    { sigla: 'SP', descricao: 'GUAPIACU' },
    { sigla: 'SP', descricao: 'GUAPIARA' },
    { sigla: 'SP', descricao: 'GUARA' },
    { sigla: 'SP', descricao: 'GUARACAI' },
    { sigla: 'SP', descricao: 'GUARACI' },
    { sigla: 'SP', descricao: 'GUARANTA' },
    { sigla: 'SP', descricao: 'GUARARAPES' },
    { sigla: 'SP', descricao: 'GUARAREMA' },
    { sigla: 'SP', descricao: 'GUARATINGUETA' },
    { sigla: 'SP', descricao: 'GUAREI' },
    { sigla: 'SP', descricao: 'GUARIBA' },
    { sigla: 'SP', descricao: 'GUARUJA' },
    { sigla: 'SP', descricao: 'GUARULHOS' },
    { sigla: 'SP', descricao: 'GUATAPARA' },
    { sigla: 'SP', descricao: 'GUZOLANDIA' },
    { sigla: 'SP', descricao: 'HERCULANDIA' },
    { sigla: 'SP', descricao: 'HOLAMBRA' },
    { sigla: 'SP', descricao: 'HORTOLANDIA' },
    { sigla: 'SP', descricao: 'IACANGA' },
    { sigla: 'SP', descricao: 'IACRI' },
    { sigla: 'SP', descricao: 'IARAS' },
    { sigla: 'SP', descricao: 'IBATE' },
    { sigla: 'SP', descricao: 'IBIRA' },
    { sigla: 'SP', descricao: 'IBIRAREMA' },
    { sigla: 'SP', descricao: 'IBITINGA' },
    { sigla: 'SP', descricao: 'IBIUNA' },
    { sigla: 'SP', descricao: 'ICEM' },
    { sigla: 'SP', descricao: 'IEPE' },
    { sigla: 'SP', descricao: 'IGARACU DO TIETE' },
    { sigla: 'SP', descricao: 'IGARAPAVA' },
    { sigla: 'SP', descricao: 'IGARATA' },
    { sigla: 'SP', descricao: 'IGUAPE' },
    { sigla: 'SP', descricao: 'ILHA COMPRIDA' },
    { sigla: 'SP', descricao: 'ILHA SOLTEIRA' },
    { sigla: 'SP', descricao: 'ILHABELA' },
    { sigla: 'SP', descricao: 'INDAIATUBA' },
    { sigla: 'SP', descricao: 'INDIANA' },
    { sigla: 'SP', descricao: 'INDIAPORA' },
    { sigla: 'SP', descricao: 'INUBIA PAULISTA' },
    { sigla: 'SP', descricao: 'IPAUSSU' },
    { sigla: 'SP', descricao: 'IPERO' },
    { sigla: 'SP', descricao: 'IPEUNA' },
    { sigla: 'SP', descricao: 'IPIGUA' },
    { sigla: 'SP', descricao: 'IPORANGA' },
    { sigla: 'SP', descricao: 'IPUA' },
    { sigla: 'SP', descricao: 'IRACEMAPOLIS' },
    { sigla: 'SP', descricao: 'IRAPUA' },
    { sigla: 'SP', descricao: 'IRAPURU' },
    { sigla: 'SP', descricao: 'ITABERA' },
    { sigla: 'SP', descricao: 'ITAI' },
    { sigla: 'SP', descricao: 'ITAJOBI' },
    { sigla: 'SP', descricao: 'ITAJU' },
    { sigla: 'SP', descricao: 'ITANHAEM' },
    { sigla: 'SP', descricao: 'ITAOCA' },
    { sigla: 'SP', descricao: 'ITAPECERICA DA SERRA' },
    { sigla: 'SP', descricao: 'ITAPETININGA' },
    { sigla: 'SP', descricao: 'ITAPEVA' },
    { sigla: 'SP', descricao: 'ITAPEVI' },
    { sigla: 'SP', descricao: 'ITAPIRA' },
    { sigla: 'SP', descricao: 'ITAPIRAPUA PAULISTA' },
    { sigla: 'SP', descricao: 'ITAPOLIS' },
    { sigla: 'SP', descricao: 'ITAPORANGA' },
    { sigla: 'SP', descricao: 'ITAPUI' },
    { sigla: 'SP', descricao: 'ITAPURA' },
    { sigla: 'SP', descricao: 'ITAQUAQUECETUBA' },
    { sigla: 'SP', descricao: 'ITARARE' },
    { sigla: 'SP', descricao: 'ITARIRI' },
    { sigla: 'SP', descricao: 'ITATIBA' },
    { sigla: 'SP', descricao: 'ITATINGA' },
    { sigla: 'SP', descricao: 'ITIRAPINA' },
    { sigla: 'SP', descricao: 'ITIRAPUA' },
    { sigla: 'SP', descricao: 'ITOBI' },
    { sigla: 'SP', descricao: 'ITU' },
    { sigla: 'SP', descricao: 'ITUPEVA' },
    { sigla: 'SP', descricao: 'ITUVERAVA' },
    { sigla: 'SP', descricao: 'JABORANDI' },
    { sigla: 'SP', descricao: 'JABOTICABAL' },
    { sigla: 'SP', descricao: 'JACAREI' },
    { sigla: 'SP', descricao: 'JACI' },
    { sigla: 'SP', descricao: 'JACUPIRANGA' },
    { sigla: 'SP', descricao: 'JAGUARIUNA' },
    { sigla: 'SP', descricao: 'JALES' },
    { sigla: 'SP', descricao: 'JAMBEIRO' },
    { sigla: 'SP', descricao: 'JANDIRA' },
    { sigla: 'SP', descricao: 'JARAGUA' },
    { sigla: 'SP', descricao: 'JARDINOPOLIS' },
    { sigla: 'SP', descricao: 'JARINU' },
    { sigla: 'SP', descricao: 'JAU' },
    { sigla: 'SP', descricao: 'JERIQUARA' },
    { sigla: 'SP', descricao: 'JOANOPOLIS' },
    { sigla: 'SP', descricao: 'JOAO RAMALHO' },
    { sigla: 'SP', descricao: 'JOSE BONIFACIO' },
    { sigla: 'SP', descricao: 'JULIO MESQUITA' },
    { sigla: 'SP', descricao: 'JUMIRIM' },
    { sigla: 'SP', descricao: 'JUNDIAI' },
    { sigla: 'SP', descricao: 'JUNQUEIROPOLIS' },
    { sigla: 'SP', descricao: 'JUQUIA' },
    { sigla: 'SP', descricao: 'JUQUITIBA' },
    { sigla: 'SP', descricao: 'LAGOINHA' },
    { sigla: 'SP', descricao: 'LARANJAL PAULISTA' },
    { sigla: 'SP', descricao: 'LAVINIA' },
    { sigla: 'SP', descricao: 'LAVRINHAS' },
    { sigla: 'SP', descricao: 'LEME' },
    { sigla: 'SP', descricao: 'LENCOIS PAULISTA' },
    { sigla: 'SP', descricao: 'LIMEIRA' },
    { sigla: 'SP', descricao: 'LINDOIA' },
    { sigla: 'SP', descricao: 'LINS' },
    { sigla: 'SP', descricao: 'LORENA' },
    { sigla: 'SP', descricao: 'LOURDES' },
    { sigla: 'SP', descricao: 'LOUVEIRA' },
    { sigla: 'SP', descricao: 'LUCELIA' },
    { sigla: 'SP', descricao: 'LUCIANOPOLIS' },
    { sigla: 'SP', descricao: 'LUIS ANTONIO' },
    { sigla: 'SP', descricao: 'LUIZIANIA' },
    { sigla: 'SP', descricao: 'LUPERCIO' },
    { sigla: 'SP', descricao: 'LUTECIA' },
    { sigla: 'SP', descricao: 'MACATUBA' },
    { sigla: 'SP', descricao: 'MACAUBAL' },
    { sigla: 'SP', descricao: 'MAGDA' },
    { sigla: 'SP', descricao: 'MAIRINQUE' },
    { sigla: 'SP', descricao: 'MAIRIPORA' },
    { sigla: 'SP', descricao: 'MANDURI' },
    { sigla: 'SP', descricao: 'MARABA PAULISTA' },
    { sigla: 'SP', descricao: 'MARACAI' },
    { sigla: 'SP', descricao: 'MARAPOAMA' },
    { sigla: 'SP', descricao: 'MARIAPOLIS' },
    { sigla: 'SP', descricao: 'MARILIA' },
    { sigla: 'SP', descricao: 'MARTINOPOLIS' },
    { sigla: 'SP', descricao: 'MATAO' },
    { sigla: 'SP', descricao: 'MAUA' },
    { sigla: 'SP', descricao: 'MENDONCA' },
    { sigla: 'SP', descricao: 'MERIDIANO' },
    { sigla: 'SP', descricao: 'MESOPOLIS' },
    { sigla: 'SP', descricao: 'MIGUELOPOLIS' },
    { sigla: 'SP', descricao: 'MINEIROS DO TIETE' },
    { sigla: 'SP', descricao: 'MIRA ESTRELA' },
    { sigla: 'SP', descricao: 'MIRACATU' },
    { sigla: 'SP', descricao: 'MIRANDOPOLIS' },
    { sigla: 'SP', descricao: 'MIRANTE DO PARANAPANEMA' },
    { sigla: 'SP', descricao: 'MIRASSOL' },
    { sigla: 'SP', descricao: 'MIRASSOLANDIA' },
    { sigla: 'SP', descricao: 'MOCOCA' },
    { sigla: 'SP', descricao: 'MOGI DAS CRUZES' },
    { sigla: 'SP', descricao: 'MOGI GUACU' },
    { sigla: 'SP', descricao: 'MOGI MIRIM' },
    { sigla: 'SP', descricao: 'MOMBUCA' },
    { sigla: 'SP', descricao: 'MONCOES' },
    { sigla: 'SP', descricao: 'MONGAGUA' },
    { sigla: 'SP', descricao: 'MONTE ALEGRE DO SUL' },
    { sigla: 'SP', descricao: 'MONTE ALTO' },
    { sigla: 'SP', descricao: 'MONTE APRAZIVEL' },
    { sigla: 'SP', descricao: 'MONTE AZUL PAULISTA' },
    { sigla: 'SP', descricao: 'MONTE CASTELO' },
    { sigla: 'SP', descricao: 'MONTE MOR' },
    { sigla: 'SP', descricao: 'MONTEIRO LOBATO' },
    { sigla: 'SP', descricao: 'MORRO AGUDO' },
    { sigla: 'SP', descricao: 'MORUNGABA' },
    { sigla: 'SP', descricao: 'MOTUCA' },
    { sigla: 'SP', descricao: 'MURUTINGA DO SUL' },
    { sigla: 'SP', descricao: 'NANTES' },
    { sigla: 'SP', descricao: 'NARANDIBA' },
    { sigla: 'SP', descricao: 'NATIVIDADE DA SERRA' },
    { sigla: 'SP', descricao: 'NAZARE PAULISTA' },
    { sigla: 'SP', descricao: 'NEVES PAULISTA' },
    { sigla: 'SP', descricao: 'NHANDEARA' },
    { sigla: 'SP', descricao: 'NIPOA' },
    { sigla: 'SP', descricao: 'NOVA ALIANCA' },
    { sigla: 'SP', descricao: 'NOVA CAMPINA' },
    { sigla: 'SP', descricao: 'NOVA CANAA PAULISTA' },
    { sigla: 'SP', descricao: 'NOVA CASTILHO' },
    { sigla: 'SP', descricao: 'NOVA EUROPA' },
    { sigla: 'SP', descricao: 'NOVA GRANADA' },
    { sigla: 'SP', descricao: 'NOVA GUATAPORANGA' },
    { sigla: 'SP', descricao: 'NOVA INDEPENDENCIA' },
    { sigla: 'SP', descricao: 'NOVA LUZITANIA' },
    { sigla: 'SP', descricao: 'NOVA ODESSA' },
    { sigla: 'SP', descricao: 'NOVAIS' },
    { sigla: 'SP', descricao: 'NOVO HORIZONTE' },
    { sigla: 'SP', descricao: 'NUPORANGA' },
    { sigla: 'SP', descricao: 'OCAUCU' },
    { sigla: 'SP', descricao: 'OLEO' },
    { sigla: 'SP', descricao: 'OLIMPIA' },
    { sigla: 'SP', descricao: 'ONDA VERDE' },
    { sigla: 'SP', descricao: 'ORIENTE' },
    { sigla: 'SP', descricao: 'ORINDIUVA' },
    { sigla: 'SP', descricao: 'ORLANDIA' },
    { sigla: 'SP', descricao: 'OSASCO' },
    { sigla: 'SP', descricao: 'OSCAR BRESSANE' },
    { sigla: 'SP', descricao: 'OSVALDO CRUZ' },
    { sigla: 'SP', descricao: 'OURINHOS' },
    { sigla: 'SP', descricao: 'OURO VERDE' },
    { sigla: 'SP', descricao: 'OUROESTE' },
    { sigla: 'SP', descricao: 'PACAEMBU' },
    { sigla: 'SP', descricao: 'PALESTINA' },
    { sigla: 'SP', descricao: 'PALMARES PAULISTA' },
    { sigla: 'SP', descricao: 'PALMEIRA DO OESTE' },
    { sigla: 'SP', descricao: 'PALMITAL' },
    { sigla: 'SP', descricao: 'PANORAMA' },
    { sigla: 'SP', descricao: 'PARAGUACU PAULISTA' },
    { sigla: 'SP', descricao: 'PARAIBUNA' },
    { sigla: 'SP', descricao: 'PARAISO' },
    { sigla: 'SP', descricao: 'PARANAPANEMA' },
    { sigla: 'SP', descricao: 'PARANAPUA' },
    { sigla: 'SP', descricao: 'PARAPUA' },
    { sigla: 'SP', descricao: 'PARDINHO' },
    { sigla: 'SP', descricao: 'PARIQUERA ACU' },
    { sigla: 'SP', descricao: 'PARISI' },
    { sigla: 'SP', descricao: 'PATROCINIO PAULISTA' },
    { sigla: 'SP', descricao: 'PAULICEIA' },
    { sigla: 'SP', descricao: 'PAULINIA' },
    { sigla: 'SP', descricao: 'PAULISTANIA' },
    { sigla: 'SP', descricao: 'PAULO DE FARIA' },
    { sigla: 'SP', descricao: 'PEDERNEIRAS' },
    { sigla: 'SP', descricao: 'PEDRA BELA' },
    { sigla: 'SP', descricao: 'PEDRANOPOLIS' },
    { sigla: 'SP', descricao: 'PEDREGULHO' },
    { sigla: 'SP', descricao: 'PEDREIRA' },
    { sigla: 'SP', descricao: 'PEDRINHAS PAULISTA' },
    { sigla: 'SP', descricao: 'PEDRO DE TOLEDO' },
    { sigla: 'SP', descricao: 'PENAPOLIS' },
    { sigla: 'SP', descricao: 'PEREIRA BARRETO' },
    { sigla: 'SP', descricao: 'PEREIRAS' },
    { sigla: 'SP', descricao: 'PERUIBE' },
    { sigla: 'SP', descricao: 'PIACATU' },
    { sigla: 'SP', descricao: 'PIEDADE' },
    { sigla: 'SP', descricao: 'PILAR DO SUL' },
    { sigla: 'SP', descricao: 'PINDAMONHANGABA' },
    { sigla: 'SP', descricao: 'PINDORAMA' },
    { sigla: 'SP', descricao: 'PINHALZINHO' },
    { sigla: 'SP', descricao: 'PIQUEROBI' },
    { sigla: 'SP', descricao: 'PIQUETE' },
    { sigla: 'SP', descricao: 'PIRACAIA' },
    { sigla: 'SP', descricao: 'PIRACICABA' },
    { sigla: 'SP', descricao: 'PIRAJU' },
    { sigla: 'SP', descricao: 'PIRAJUI' },
    { sigla: 'SP', descricao: 'PIRANGI' },
    { sigla: 'SP', descricao: 'PIRAPORA DO BOM JESUS' },
    { sigla: 'SP', descricao: 'PIRAPOZINHO' },
    { sigla: 'SP', descricao: 'PIRASSUNUNGA' },
    { sigla: 'SP', descricao: 'PIRATININGA' },
    { sigla: 'SP', descricao: 'PITANGUEIRAS' },
    { sigla: 'SP', descricao: 'PLANALTO' },
    { sigla: 'SP', descricao: 'PLATINA' },
    { sigla: 'SP', descricao: 'POA' },
    { sigla: 'SP', descricao: 'POLONI' },
    { sigla: 'SP', descricao: 'POMPEIA' },
    { sigla: 'SP', descricao: 'PONGAI' },
    { sigla: 'SP', descricao: 'PONTAL' },
    { sigla: 'SP', descricao: 'PONTALINDA' },
    { sigla: 'SP', descricao: 'PONTES GESTAL' },
    { sigla: 'SP', descricao: 'POPULINA' },
    { sigla: 'SP', descricao: 'PORANGABA' },
    { sigla: 'SP', descricao: 'PORTO FELIZ' },
    { sigla: 'SP', descricao: 'PORTO FERREIRA' },
    { sigla: 'SP', descricao: 'POTIM' },
    { sigla: 'SP', descricao: 'POTIRENDABA' },
    { sigla: 'SP', descricao: 'PRACINHA' },
    { sigla: 'SP', descricao: 'PRADOPOLIS' },
    { sigla: 'SP', descricao: 'PRAIA GRANDE' },
    { sigla: 'SP', descricao: 'PRATANIA' },
    { sigla: 'SP', descricao: 'PRESIDENTE ALVES' },
    { sigla: 'SP', descricao: 'PRESIDENTE BERNARDES' },
    { sigla: 'SP', descricao: 'PRESIDENTE EPITACIO' },
    { sigla: 'SP', descricao: 'PRESIDENTE PRUDENTE' },
    { sigla: 'SP', descricao: 'PRESIDENTE VENCESLAU' },
    { sigla: 'SP', descricao: 'PROMISSAO' },
    { sigla: 'SP', descricao: 'QUADRA' },
    { sigla: 'SP', descricao: 'QUATA' },
    { sigla: 'SP', descricao: 'QUEIROZ' },
    { sigla: 'SP', descricao: 'QUELUZ' },
    { sigla: 'SP', descricao: 'QUINTANA' },
    { sigla: 'SP', descricao: 'RAFARD' },
    { sigla: 'SP', descricao: 'RANCHARIA' },
    { sigla: 'SP', descricao: 'REDENCAO DA SERRA' },
    { sigla: 'SP', descricao: 'REGENTE FEIJO' },
    { sigla: 'SP', descricao: 'REGINOPOLIS' },
    { sigla: 'SP', descricao: 'REGISTRO' },
    { sigla: 'SP', descricao: 'RESTINGA' },
    { sigla: 'SP', descricao: 'RIBEIRA' },
    { sigla: 'SP', descricao: 'RIBEIRAO BONITO' },
    { sigla: 'SP', descricao: 'RIBEIRAO BRANCO' },
    { sigla: 'SP', descricao: 'RIBEIRAO CORRENTE' },
    { sigla: 'SP', descricao: 'RIBEIRAO DO SUL' },
    { sigla: 'SP', descricao: 'RIBEIRAO DOS INDIOS' },
    { sigla: 'SP', descricao: 'RIBEIRAO GRANDE' },
    { sigla: 'SP', descricao: 'RIBEIRAO PIRES' },
    { sigla: 'SP', descricao: 'RIBEIRAO PRETO' },
    { sigla: 'SP', descricao: 'RIFAINA' },
    { sigla: 'SP', descricao: 'RINCAO' },
    { sigla: 'SP', descricao: 'RINOPOLIS' },
    { sigla: 'SP', descricao: 'RIO CLARO' },
    { sigla: 'SP', descricao: 'RIO DAS PEDRAS' },
    { sigla: 'SP', descricao: 'RIO GRANDE DA SERRA' },
    { sigla: 'SP', descricao: 'RIOLANDIA' },
    { sigla: 'SP', descricao: 'RIVERSUL' },
    { sigla: 'SP', descricao: 'ROSANA' },
    { sigla: 'SP', descricao: 'ROSEIRA' },
    { sigla: 'SP', descricao: 'RUBIACEA' },
    { sigla: 'SP', descricao: 'RUBINEIA' },
    { sigla: 'SP', descricao: 'SABINO' },
    { sigla: 'SP', descricao: 'SAGRES' },
    { sigla: 'SP', descricao: 'SALES' },
    { sigla: 'SP', descricao: 'SALES OLIVEIRA' },
    { sigla: 'SP', descricao: 'SALESOPOLIS' },
    { sigla: 'SP', descricao: 'SALMOURAO' },
    { sigla: 'SP', descricao: 'SALTINHO' },
    { sigla: 'SP', descricao: 'SALTO' },
    { sigla: 'SP', descricao: 'SALTO DE PIRAPORA' },
    { sigla: 'SP', descricao: 'SALTO GRANDE' },
    { sigla: 'SP', descricao: 'SANDOVALINA' },
    { sigla: 'SP', descricao: 'SANTA ADELIA' },
    { sigla: 'SP', descricao: 'SANTA ALBERTINA' },
    { sigla: 'SP', descricao: 'SANTA BARBARA D OESTE' },
    { sigla: 'SP', descricao: 'SANTA BRANCA' },
    { sigla: 'SP', descricao: 'SANTA CLARA DO OESTE' },
    { sigla: 'SP', descricao: 'SANTA CRUZ DA CONCEICAO' },
    { sigla: 'SP', descricao: 'SANTA CRUZ DA ESPERANCA' },
    { sigla: 'SP', descricao: 'SANTA CRUZ DAS PALMEIRAS' },
    { sigla: 'SP', descricao: 'SANTA CRUZ DO RIO PARDO' },
    { sigla: 'SP', descricao: 'SANTA ERNESTINA' },
    { sigla: 'SP', descricao: 'SANTA FE DO SUL' },
    { sigla: 'SP', descricao: 'SANTA GERTRUDES' },
    { sigla: 'SP', descricao: 'SANTA ISABEL' },
    { sigla: 'SP', descricao: 'SANTA LUCIA' },
    { sigla: 'SP', descricao: 'SANTA MARIA DA SERRA' },
    { sigla: 'SP', descricao: 'SANTA MERCEDES' },
    { sigla: 'SP', descricao: 'SANTA RITA DO OESTE' },
    { sigla: 'SP', descricao: 'SANTA RITA DO PASSA QUATR' },
    { sigla: 'SP', descricao: 'SANTA ROSA DE VITERBO' },
    { sigla: 'SP', descricao: 'SANTA SALETE' },
    { sigla: 'SP', descricao: 'SANTANA DA PONTE PENSA' },
    { sigla: 'SP', descricao: 'SANTANA DE PARNAIBA' },
    { sigla: 'SP', descricao: 'SANTO ANASTACIO' },
    { sigla: 'SP', descricao: 'SANTO ANDRE' },
    { sigla: 'SP', descricao: 'SANTO ANTONIO D ARACANGUA' },
    { sigla: 'SP', descricao: 'SANTO ANTONIO DA ALEGRIA' },
    { sigla: 'SP', descricao: 'SANTO ANTONIO DE POSSE' },
    { sigla: 'SP', descricao: 'SANTO ANTONIO DO JARDIM' },
    { sigla: 'SP', descricao: 'SANTO ANTONIO DO PINHAL' },
    { sigla: 'SP', descricao: 'SANTO EXPEDITO' },
    { sigla: 'SP', descricao: 'SANTOPOLIS DO AGUAPEI' },
    { sigla: 'SP', descricao: 'SANTOS' },
    { sigla: 'SP', descricao: 'SAO BENTO DO SAPUCAI' },
    { sigla: 'SP', descricao: 'SAO BERNARDO DO CAMPO' },
    { sigla: 'SP', descricao: 'SAO CAETANO DO SUL' },
    { sigla: 'SP', descricao: 'SAO CARLOS' },
    { sigla: 'SP', descricao: 'SAO FRANCISCO' },
    { sigla: 'SP', descricao: 'SAO JOAO DA BOA VISTA' },
    { sigla: 'SP', descricao: 'SAO JOAO DAS DUAS PONTES' },
    { sigla: 'SP', descricao: 'SAO JOAO DE IRACEMA' },
    { sigla: 'SP', descricao: 'SAO JOAO DO PAU D ALHO' },
    { sigla: 'SP', descricao: 'SAO JOAQUIM DA BARRA' },
    { sigla: 'SP', descricao: 'SAO JOSE DA BELA VISTA' },
    { sigla: 'SP', descricao: 'SAO JOSE DO BARREIRO' },
    { sigla: 'SP', descricao: 'SAO JOSE DO RIO PARDO' },
    { sigla: 'SP', descricao: 'SAO JOSE DO RIO PRETO' },
    { sigla: 'SP', descricao: 'SAO JOSE DOS CAMPOS' },
    { sigla: 'SP', descricao: 'SAO LOURENCO DA SERRA' },
    { sigla: 'SP', descricao: 'SAO LUIS DO PARAITINGA' },
    { sigla: 'SP', descricao: 'SAO MANUEL' },
    { sigla: 'SP', descricao: 'SAO MIGUEL ARCANJO' },
    { sigla: 'SP', descricao: 'SAO PAULO' },
    { sigla: 'SP', descricao: 'SAO PEDRO' },
    { sigla: 'SP', descricao: 'SAO PEDRO DO TURVO' },
    { sigla: 'SP', descricao: 'SAO ROQUE' },
    { sigla: 'SP', descricao: 'SAO SEBASTIAO' },
    { sigla: 'SP', descricao: 'SAO SEBASTIAO DA GRAMA' },
    { sigla: 'SP', descricao: 'SAO SIMAO' },
    { sigla: 'SP', descricao: 'SAO VICENTE' },
    { sigla: 'SP', descricao: 'SARAPUI' },
    { sigla: 'SP', descricao: 'SARUTAIA' },
    { sigla: 'SP', descricao: 'SEBASTIANOPOLIS DO SUL' },
    { sigla: 'SP', descricao: 'SERRA AZUL' },
    { sigla: 'SP', descricao: 'SERRA NEGRA' },
    { sigla: 'SP', descricao: 'SERRANA' },
    { sigla: 'SP', descricao: 'SERTAOZINHO' },
    { sigla: 'SP', descricao: 'SETE BARRAS' },
    { sigla: 'SP', descricao: 'SEVERINIA' },
    { sigla: 'SP', descricao: 'SILVEIRAS' },
    { sigla: 'SP', descricao: 'SOCORRO' },
    { sigla: 'SP', descricao: 'SOROCABA' },
    { sigla: 'SP', descricao: 'SUD MENNUCCI' },
    { sigla: 'SP', descricao: 'SUMARE' },
    { sigla: 'SP', descricao: 'SUZANAPOLIS' },
    { sigla: 'SP', descricao: 'SUZANO' },
    { sigla: 'SP', descricao: 'TABAPUA' },
    { sigla: 'SP', descricao: 'TABATINGA' },
    { sigla: 'SP', descricao: 'TABOAO DA SERRA' },
    { sigla: 'SP', descricao: 'TACIBA' },
    { sigla: 'SP', descricao: 'TAGUAI' },
    { sigla: 'SP', descricao: 'TAIACU' },
    { sigla: 'SP', descricao: 'TAIUVA' },
    { sigla: 'SP', descricao: 'TAMBAU' },
    { sigla: 'SP', descricao: 'TANABI' },
    { sigla: 'SP', descricao: 'TAPIRAI' },
    { sigla: 'SP', descricao: 'TAPIRATIBA' },
    { sigla: 'SP', descricao: 'TAQUARAL' },
    { sigla: 'SP', descricao: 'TAQUARITINGA' },
    { sigla: 'SP', descricao: 'TAQUARITUBA' },
    { sigla: 'SP', descricao: 'TAQUARIVAI' },
    { sigla: 'SP', descricao: 'TARABAI' },
    { sigla: 'SP', descricao: 'TARUMA' },
    { sigla: 'SP', descricao: 'TATUI' },
    { sigla: 'SP', descricao: 'TAUBATE' },
    { sigla: 'SP', descricao: 'TEJUPA' },
    { sigla: 'SP', descricao: 'TEODORO SAMPAIO' },
    { sigla: 'SP', descricao: 'TERRA ROXA' },
    { sigla: 'SP', descricao: 'TIETE' },
    { sigla: 'SP', descricao: 'TIMBURI' },
    { sigla: 'SP', descricao: 'TORRE DE PEDRA' },
    { sigla: 'SP', descricao: 'TORRINHA' },
    { sigla: 'SP', descricao: 'TRABIJU' },
    { sigla: 'SP', descricao: 'TREMEMBE' },
    { sigla: 'SP', descricao: 'TRES FRONTEIRAS' },
    { sigla: 'SP', descricao: 'TUIUTI' },
    { sigla: 'SP', descricao: 'TUPA' },
    { sigla: 'SP', descricao: 'TUPI PAULISTA' },
    { sigla: 'SP', descricao: 'TURIUBA' },
    { sigla: 'SP', descricao: 'TURMALINA' },
    { sigla: 'SP', descricao: 'UBARANA' },
    { sigla: 'SP', descricao: 'UBATUBA' },
    { sigla: 'SP', descricao: 'UBIRAJARA' },
    { sigla: 'SP', descricao: 'UCHOA' },
    { sigla: 'SP', descricao: 'UNIAO PAULISTA' },
    { sigla: 'SP', descricao: 'URANIA' },
    { sigla: 'SP', descricao: 'URU' },
    { sigla: 'SP', descricao: 'URUPES' },
    { sigla: 'SP', descricao: 'VALENTIM GENTIL' },
    { sigla: 'SP', descricao: 'VALINHOS' },
    { sigla: 'SP', descricao: 'VALPARAISO' },
    { sigla: 'SP', descricao: 'VARGEM' },
    { sigla: 'SP', descricao: 'VARGEM GRANDE DO SUL' },
    { sigla: 'SP', descricao: 'VARGEM GRANDE PAULISTA' },
    { sigla: 'SP', descricao: 'VARZEA PAULISTA' },
    { sigla: 'SP', descricao: 'VERA CRUZ' },
    { sigla: 'SP', descricao: 'VINHEDO' },
    { sigla: 'SP', descricao: 'VIRADOURO' },
    { sigla: 'SP', descricao: 'VISTA ALEGRE DO ALTO' },
    { sigla: 'SP', descricao: 'VITORIA BRASIL' },
    { sigla: 'SP', descricao: 'VOTORANTIM' },
    { sigla: 'SP', descricao: 'VOTUPORANGA' },
    { sigla: 'SP', descricao: 'ZACARIAS' },
    { sigla: 'TO', descricao: 'ALMAS' },
    { sigla: 'TO', descricao: 'ALVORADA' },
    { sigla: 'TO', descricao: 'ARAGUAINA' },
    { sigla: 'TO', descricao: 'CARIRI DO TOCANTINS' },
    { sigla: 'TO', descricao: 'CHAPADA DA NATIVIDADE' },
    { sigla: 'TO', descricao: 'GUARAI' },
    { sigla: 'TO', descricao: 'GURUPI' },
    { sigla: 'TO', descricao: 'MIRACEMA DO TOCANTINS' },
    { sigla: 'TO', descricao: 'NOVA OLINDA' },
    { sigla: 'TO', descricao: 'PALMAS' },
    { sigla: 'TO', descricao: 'PEDRO AFONSO' },
    { sigla: 'TO', descricao: 'SAO SALVADOR DO TOCANTINS' }
  ];

  getCidades() {
    return this.cidades;
  }
}
